### ISSUE TITLE
Finding local volunteers across India for Promotions

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#1]
- [ ] Send a mail to mailing list for call for volunteers

**Comment by realslimshanky** [comment]
It would be great to broadcast the news that a call for promotional volunteers in on to different mailing lists. Here are some to begin with
- Local python user groups as mentioned on PSSI website - https://web.archive.org/web/20170206120448/pssi.org.in/usergroups/
- Free software communities of India - https://fsug.in/

**Comment by bravegnu** [comment]
@realslimshanky I suggest that we invite the meetup group organizers to help us out with it, by writing directly writing to them. Writing mails directly to people, generally increases the chances of getting a positive response (compared to a broadcast)

**Comment by bravegnu** [comment]
OK. On second thought we will first send out broadcast mails to the mailing lists, as indicated by @realslimshanky . If there are no takers, we will contact the meetup group organizers. @realslimshanky Would you be interested in taking this up?

**Comment by bravegnu** [comment]
Superseded by #44
