### ISSUE TITLE
Poster for Whatsapp Promotion

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#100]
![whatsapp](https://user-images.githubusercontent.com/1171852/58759773-1d2d6100-854d-11e9-998e-7cba79734b1f.jpg)

**Comment by bravegnu** [comment]
@rajkumartreads Do we have a text to go with the image?

**Comment by bravegnu** [comment]
We could use the text: "Book your tickets for PyCon India 2019 at https://in.pycon.org/"

**Comment by abhishekmishragithub** [comment]
@bravegnu we are good to go ?

**Comment by laxmena** [comment]
Facebook videos or Instagram can now be played as Picture in Picture mode. So we could make a short video clippings of 15 to 30 seconds each that can be shared as Whatsapp Status. And about 45 second videos to be shared as Whatsapp messages, which can be played in Picture in Picture mode.
