### ISSUE TITLE
Poster for Early Bird Sold Out!

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#101]

**Comment by astronomersiva** [comment]
![Tickets Sold out](https://user-images.githubusercontent.com/7725225/58820776-1b4cc600-8651-11e9-9c88-5e2c331de223.png)

Courtesy: @agnes-joseph

**Comment by abhishekmishragithub** [comment]
> ![Tickets Sold out](https://user-images.githubusercontent.com/7725225/58820776-1b4cc600-8651-11e9-9c88-5e2c331de223.png)
> 
> Courtesy: @agnes-joseph

+1
