### ISSUE TITLE
Announcement for Inclusion @ PyCon India

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#102]
![inclusive](https://user-images.githubusercontent.com/1171852/58870673-43ced180-86de-11e9-937a-19f45e6dc1b0.png)

Learn about the steps taken to make PyCon India accessible and women friendly.
https://in.pycon.org/blog/2019/2019-making-pycon-india-women-friendly.html
https://in.pycon.org/blog/2019/2019-making-pycon-india-accessible-first-step.html

#Python #PyConIndia2019

**Comment by abhishekmishragithub** [comment]
+1
