### ISSUE TITLE
Poster CFP Announcement

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#103]

**Comment by bravegnu** [comment]
We need to announce CFP for posters. The CFP URL is https://in.pycon.org/cfp/posters-2019/proposals/

**Comment by agnes-joseph** [comment]
@bravegnu Ill take care this

**Comment by bravegnu** [comment]
Thanks @agnes-joseph We are planning to make the announcement tomorrow.

**Comment by agnes-joseph** [comment]
![CPF](https://user-images.githubusercontent.com/10452872/58983990-9cdd5900-87f5-11e9-9384-582a3a623198.png)


Can you see if this proper?

**Comment by bravegnu** [comment]
* The logo at the top can be a little larger. (Just make sure the "Chennai" is readable.)
   * CPF FOR POSTERS -> POSTER CFP IS OPEN!
   * Text at the bottom: Present your project and ideas, trigger discussions, and get connected with like minded folks, by presenting a poster. Learn more about posters on the Poster CFP page.

**Comment by agnes-joseph** [comment]
Noted. Will upload the changes now.

**Comment by agnes-joseph** [comment]
![CPF](https://user-images.githubusercontent.com/10452872/59006429-82c86880-883f-11e9-8db5-2066574dabf4.png)

**Comment by bravegnu** [comment]
<img src="https://user-images.githubusercontent.com/10452872/59006429-82c86880-883f-11e9-8db5-2066574dabf4.png"/>

Present your project and ideas, trigger discussions, and get connected with like minded folks, by presenting a poster. Learn more about posters on the Poster CFP page: https://in.pycon.org/cfp/posters-2019/proposals/

#Python #PyConIndia2019

**Comment by abhishekmishragithub** [comment]
> ![](https://user-images.githubusercontent.com/10452872/59006429-82c86880-883f-11e9-8db5-2066574dabf4.png)
> 
> Present your project and ideas, trigger discussions, and get connected with like minded folks, by presenting a poster. Learn more about posters on the Poster CFP page: https://in.pycon.org/cfp/posters-2019/proposals/
> 
> #Python #PyConIndia2019

+1

**Comment by bravegnu** [comment]
Subject: Call for Posters for PyCon India 2019

Hi Everyone,
The CFP for posters, for PyCon India 2019, is open!

Posters are graphical summary of projects or ideas. They are usually presented with an A0 size poster, but any creative ways are always welcome. The poster session provides an opportunity to network with the conference attendees and acts as a starting point for further discussions. While talks generally needs to appeal to a wide section of the community, posters can cover niche topics.

PyCon India 2019 will be having a poster presentation session at post lunch, day 1. During the poster presentation session you will be provided with a poster board that can hold an A0 size poster, and a table to place your laptop, for demos. Conference attendees interested in your topic, will stop by, during which you can give them a brief presentation / demo.

To submit your proposal and for more details visit https://in.pycon.org/cfp/posters-2019/proposals/

For more details about PyCon India 2019, please visit https://in.pycon.org/

Regards,
{YOUR-NAME}
