### ISSUE TITLE
Three Reasons You Should Speak at PyCon

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#107]
![why-speak-at-pycon](https://user-images.githubusercontent.com/1171852/59239593-a3b60280-8c1f-11e9-9c23-4fdadd7afee4.png)

Tech Talks Are Campfires: Jesse's Three Reasons You Should Speak At PyCon by @jessejiryudavis. Read the article at https://emptysqua.re/blog/tech-talks-are-campfires-jesses-three-reasons-you-should-speak-at-pycon/ Submit your proposal at https://in.pycon.org/2019/submit-a-proposal.html

#Python #PyConIndia2019

**Comment by abhishekmishragithub** [comment]
> ![why-speak-at-pycon](https://user-images.githubusercontent.com/1171852/59239593-a3b60280-8c1f-11e9-9c23-4fdadd7afee4.png)
> 
> Tech Talks Are Campfires: Jesse's Three Reasons You Should Speak At PyCon by @jessejiryudavis. Read the article at https://emptysqua.re/blog/tech-talks-are-campfires-jesses-three-reasons-you-should-speak-at-pycon/ Submit your proposal at https://in.pycon.org/2019/submit-a-proposal.html
> 
> #Python #PyConIndia2019

+1
