### ISSUE TITLE
Reaching out to meetup group speakers to submit talk proposal

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#109]
- [ ] ChennaiPy
- [ ] BangPyPers
- [ ] HydPy

**Comment by gnurenga** [comment]
Hi {{ speaker name}}

I am  {{your name}}, a volunteer for PyCon India 2019. We are reaching out to Python meetup group
speakers for submitting  talk proposal. We got your information from {{meetup group name}} 

PyCon India is India's premier conference on using and developing the Python programming language. This year, the conference is happening in Chennai, on October 12 - 15, 2019. About 1200 Pythonistas from all over India are expected to participate in the event. The event will consist of 4 keynotes, 36+ talks, 6+ workshops, a poster session, lightning talks, and more.

Tickets for PyCon India 2019 are now live. You can purchase them at https://in.pycon.org/

Here are ways to engage with other conference attendees:

Share your ideas, learning and experiences, through a talk. Submit your talk proposal at https://in.pycon.org/cfp/2019/proposals/ Talk CFP closes on 1st July.

Help fellow Pythonistas to ramp up on a topic, through a workshop. Submit your workshop proposal at https://in.pycon.org/cfp/workshops-2019/proposals/ Workshop CFP closes on 1st July.

Trigger discussions, and get connected with like minded folks, by presenting a poster. Submit your poster proposal at https://in.pycon.org/cfp/posters-2019/proposals/ Poster CFP closes on 1st August.

Regards
{{Your Name}}

**Comment by abhishekmishragithub** [comment]
> Hi {{ speaker name}}
> 
> I am {{your name}}, a volunteer for PyCon India 2019. We are reaching out to Python meetup group
> speakers for submitting talk proposal. We got your information from {{meetup group name}}
> 
> PyCon India is India's premier conference on using and developing the Python programming language. This year, the conference is happening in Chennai, on October 12 - 15, 2019. About 1200 Pythonistas from all over India are expected to participate in the event. The event will consist of 4 keynotes, 36+ talks, 6+ workshops, a poster session, lightning talks, and more.
> 
> Tickets for PyCon India 2019 are now live. You can purchase them at https://in.pycon.org/
> 
> Here are ways to engage with other conference attendees:
> 
> Share your ideas, learning and experiences, through a talk. Submit your talk proposal at https://in.pycon.org/cfp/2019/proposals/ Talk CFP closes on 1st July.
> 
> Help fellow Pythonistas to ramp up on a topic, through a workshop. Submit your workshop proposal at https://in.pycon.org/cfp/workshops-2019/proposals/ Workshop CFP closes on 1st July.
> 
> Trigger discussions, and get connected with like minded folks, by presenting a poster. Submit your poster proposal at https://in.pycon.org/cfp/posters-2019/proposals/ Poster CFP closes on 1st August.
> 
> Regards
> {{Your Name}}

+1

**Comment by bravegnu** [comment]
Hi {{ speaker name}}
I am {{your name}}, a volunteer for PyCon India 2019. We understand that you have been doing talks at {{meetup group name}}. It will be great if you can share your work / ideas / experiences at PyCon India 2019 http://in.pycon.org/ which is happening in Chennai, on Oct 12th - 15th.

You can submit your talk / workshop / poster proposal at https://in.pycon.org/2019/submit-a-proposal.html Looking forward to your proposal!

Regards,
{{your name}}

**Comment by gnurenga** [comment]
> Hi {{ speaker name}}
> I am {{your name}}, a volunteer for PyCon India 2019. We understand that you have been doing talks at {{meetup group name}}. It will be great if you can share your work / ideas / experiences at PyCon India 2019 http://in.pycon.org/ which is happening in Chennai, on Oct 12th - 15th.
> 
> You can submit your talk / workshop / poster proposal at https://in.pycon.org/2019/submit-a-proposal.html Looking forward tor your proposal!
> 
> Regards,
> {{your name}}

Looks simple, I will use this
