### ISSUE TITLE
Poster for Talk and Workshop CFP closes in 15 days

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#110]
We need to create a social media poster for this. Text along the lines of
``````
Talk and Workshop CFP closes in 15 days.
``````

**Comment by bravegnu** [comment]
We will need this on 17th June.

**Comment by agnes-joseph** [comment]
Will be working on this

**Comment by bravegnu** [comment]
@agnes-joseph Can we have a preview on 16th June? So that we have time for any changes.

**Comment by agnes-joseph** [comment]
![Time Up](https://user-images.githubusercontent.com/10452872/59550344-355aa280-8f87-11e9-8373-b599fcc0325a.png)
