### ISSUE TITLE
CFP Closes in 15 days

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#113]
Call for talk and workshop proposals closes in 15 days! Don't wait till the last moment to submit your proposal! Submit proposals at https://in.pycon.org/2019/submit-a-proposal.html

#Python #PyConIndia2019
![15days-cfp](https://user-images.githubusercontent.com/3196294/59562495-250bfb80-904b-11e9-8149-307308b35cb5.png)

**Comment by bravegnu** [comment]
Use the link https://in.pycon.org/2019/submit-a-proposal.html instead.

**Comment by gnurenga** [comment]
> Use the link https://in.pycon.org/2019/submit-a-proposal.html instead.

updated now in the main description

**Comment by bravegnu** [comment]
Email Announcement:

Subject: PyCon India CFP Closes in 15 Days

Hi {name},
{add-your-context-here}

PyCon India call for talk and workshop proposals is closing in 15 days. Please submit your proposal at the earliest at https://in.pycon.org/2019/submit-a-proposal.html

PyCon India is India's premier conference on using and developing the Python programming language. This year, the conference is happening in Chennai, on October 12 - 15, 2019. About 1200 Pythonistas from all over India are expected to participate in the event. The event will consist of 4 keynotes, 36+ talks, 6+ workshops, a poster session, lightning talks, and more.

For more details and to purchase tickets, please visit https://in.pycon.org/

Regards,
{your-name}
