### ISSUE TITLE
Sponsorship document in PDF format

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#12]
The sponsorship document is currently in HTML format, since we were
waiting for the website and logo design. Now that the logo and web
design elements are available we can create the document in PDF
format.

**Comment by stylesen** [comment]
First draft of PDF prospectus. Logo needs an update with new one for the slide backgrounds. Feedback, comments welcome.
[sponsorship-prospectus-2019.pdf](https://github.com/pythonindia/inpycon2019-tasks/files/3044522/sponsorship-prospectus-2019.pdf)

**Comment by astronomersiva** [comment]
I have asked for the new slides. Will update once I get them. Should be ready by tonight or tomorrow morning.

<img width="872" alt="Screen Shot 2019-04-04 at 22 04 07" src="https://user-images.githubusercontent.com/7725225/55572611-9d8a3e00-5725-11e9-9e15-e065dc6dfc08.png">

I think the text is too tightly packed. Since it's white as well, it's making it really difficult to read. We should also try and not touch the page borders. Can we try and increase the line spacing? The alignment also seems to be a bit off.

**Comment by abhishekmishragithub** [comment]
@bravegnu and @stylesen can i use this template ?

**Comment by bravegnu** [comment]
Nope, it's not finished yet.

**Comment by stylesen** [comment]
This is the second draft of PDF prospectus. I request everyone to go through it and post comment, if any. This comes with the updated logo and slide designs. @astronomersiva comments are addressed too. If there are no comments on this, I shall make it the final cut of the sponsorship prospectus PDF. 

[sponsorship-prospectus-2019-take-1.pdf](https://github.com/pythonindia/inpycon2019-tasks/files/3075897/sponsorship-prospectus-2019-take-1.pdf)

Ping - @bravegnu @abhishekmishragithub

**Comment by withshubh** [comment]
I can go ahead with the sponsorship once the prospectus is final. ✌️

**Comment by py-ranoid** [comment]
The sponsorship amounts in USD are much higher than the INR ones post-conversion. Is that intentional?

| Package | INR | USD
| -- | -- | -- |
|Platinum | ₹ 7,50,000 | $ 12000 
| Gold | ₹ 3,50,000 | $ 5400
| Silver (Startup Discount Available) | ₹ 1,75,000 | $ 2700
| Associate (Startup Discount Available) | ₹ 50,000 | $ 800

$12000 ~ 8.3 lakhs, whereas INR amount is 7.5 lakhs

**Comment by bravegnu** [comment]
Hi @stylesen thanks for the updated prospectus. A couple of backgrounds needs updating. We will be getting the updated backgrounds shortly. Pinging @astronomersiva 

Feedback:
   * I would prefer light back ground for content slides and the dark background for opening and closing. Makes things a bit uniform, and provides a good contrast for the foreground text.
   * Maintain max. of 3 or 4 font sizes
   * The second slide is little dense on information. It can be broken into two, slide 1:
``````
Title: PyCon India 2019
* 11th year of PyCon India
* Conference, at Chennai Trade Center
   - Oct 12 (Sat), Oct 13 (Sun)
* Workshop, at IITM Research Partk
   - Oct 14 (Mon)
* Devsprint, IITM Research Park
  - Oct 14 (Mon), Oct 15 (Tue)
``````
  * Slide 2: Community 
``````
Title: Community
  * Active communities in various cities across India
  * Local User Groups: 12000+ (via different mailing lists)
  * Facebook: 6400+ (likes and followers)
  * Twitter: 6500+ (followers)
``````
   * For the previous sponsors, it might not be required to list all the sponsors, may be Platinum and Gold only. The page looks a bit cramped. I would suggest a white rectangle for the area displaying all the logos.
   * The statistics from previous years can be put up on two slides. A couple of lines summarizing the data can be provided. Also the total attendance of the previous year is also necessary to give meaning to the percentages.
   * The "Flexibility" and "Startup Discount" can be moved to separate slides of their own after the "Sponsorship Benefits" slide.
  * For the sponsorship benefits the foot note on "Square Meters" can be removed, and the corresponding row heading can be changed to: Stall at Venue (size in square meters)

BTW, when you are done with the content, you can probably provide the source file, and may be the design team can tweak it for alignment, colors, and font sizing.

**Comment by satyaakam** [comment]
@bravegnu has covered most of the points about colour combination , also the graphs and pie chart of participants is not not clear.

Fonts can be made a bit large not issues if we add two more extra slides to the deck

**Comment by stylesen** [comment]
Based on comments from @bravegnu and @satyaakam I ve updated the slides - [sponsorship-prospectus-2019-take-3.pdf](https://github.com/pythonindia/inpycon2019-tasks/files/3077151/sponsorship-prospectus-2019-take-3.pdf)

The source for the presentation is available here - https://www.dropbox.com/s/fiszoke8za5wpiw/sponsorship-prospectus-2019.odp?dl=0

**Comment by bravegnu** [comment]
@stylesen The slides look much better now! Here are a few more suggestions:

  * The audience profile in slide 8, seems to just re-iterate the data from slide 6. It can be dropped? And the rest of the text can get a better font size?
  * Startup Discount slide can be moved after the sponsorship packages.
  * Flexibility slide can be moved after the sponsorship benefits slides. Seems more logical this way.
  * The sponsorship benefits table can be broken down to two slides. There are so many table rows crammed into a single slide. The last 4 benefits can be moved to a separate slide.
  * The title for slides 6 and 7 can be changed from the current "Statistics from Previous Year (2018)" to "Attendee Profile" or "Demographics"
  * The bullets in slides 6, can rephrased as follows?
``````
  * A total of 1454 people participated in PyCon India 2018
  * 78% of the attendees were from the industry, and 32% were students
``````
  * The bullets in slides 7, can be rephrased as follows?
``````
  * Attendees had diversified experience levels
  * More than half of the attendees were experienced (1-15+ years)
``````

**Comment by stylesen** [comment]
> The sponsorship amounts in USD are much higher than the INR ones post-conversion. Is that intentional?

Yes that is intentional considering the overheads involved in getting incoming remittance and other taxes associated with it.

**Comment by stylesen** [comment]
> @stylesen The slides look much better now! Here are a few more suggestions:

@bravegnu I ve addressed all the comments from you and the updated version of the presentation is here - [sponsorship-prospectus-2019-take-4.pdf](https://github.com/pythonindia/inpycon2019-tasks/files/3082958/sponsorship-prospectus-2019-take-4.pdf)

**Comment by bravegnu** [comment]
Looks good @stylesen Can you please share the updated source file. I will ask @babuenir to fine tune the design, while maintaining the content.

**Comment by bravegnu** [comment]
@babuenir One of the slides' background needs to be updated. The updated background is under review: https://github.com/pythonindia/inpycon2019-tasks/pull/41 We will get it merged shortly.

**Comment by stylesen** [comment]
> Looks good @stylesen Can you please share the updated source file. I will ask @babuenir to fine tune the design, while maintaining the content.

Hi @bravegnu and @babuenir I updated slide-3 with the updated background and here is the PDF - 
[sponsorship-prospectus-2019-take-5.pdf](https://github.com/pythonindia/inpycon2019-tasks/files/3084973/sponsorship-prospectus-2019-take-5.pdf)

The updated source file is here - https://www.dropbox.com/s/fiszoke8za5wpiw/sponsorship-prospectus-2019.odp?dl=0

**Comment by babuenir** [comment]
Hi @bravegnu and @stylesen, 
The look and feel of the design is updated. And the odp and pdf files are available at,
https://www.dropbox.com/s/nre6auupc8xespr/sponsorship-prospectus-2019.odp?dl=0
https://www.dropbox.com/s/ikdhgtz2wpp8fph/sponsorship-prospectus-2019.pdf?dl=0

**Comment by bravegnu** [comment]
Applied @babuenir charts on the latest slides https://docs.google.com/presentation/d/17kJFs281u49ROMJ1wrDw0bWf5Y6JzXBw_hptU04vjsw/edit?usp=sharing

**Comment by stylesen** [comment]
Sponsorship Prospectus 2019 PDF final cut - [sponsorship-prospectus-2019-final.pdf](https://github.com/pythonindia/inpycon2019-tasks/files/3093807/sponsorship-prospectus-2019-final.pdf)

**Comment by bravegnu** [comment]
The latest version is available from https://github.com/pythonindia/inpycon2019-tasks/blob/master/sponsorship-prospectus.pdf

**Comment by stylesen** [comment]
The PDF document is up in the website https://in.pycon.org/2019/index.html#sponsorship hence closing this issue.
