### ISSUE TITLE
CFP 1 Day to Go.

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#122]
![cfp-1-day](https://user-images.githubusercontent.com/1171852/60387329-f36d4880-9abe-11e9-98a1-7b509dac2d50.png)

The clock is ticking, only 1 more day left to submit your talk / workshop proposal!

#Python #PyConIndia2019

###################### SPLIT TWEET HERE ######################

Tip #4: Spice up the Tutorial!

If you would like to do a tutorial style talk on a tool / library / framework, make sure you weave in your own experience or spice it up with interesting examples and use cases.

Whatever you do, do not repeat what is easily available from the docs.

**Comment by astronomersiva** [comment]
..... available in the docs.

**Comment by bravegnu** [comment]
@astronomersiva  I would have to drop the "easily" then.
