### ISSUE TITLE
Open CFP for Devsprints

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#126]
We will have to open CFP for devsprints, so that we can open the Devsprint tickets after the workshop tickets.

**Comment by bravegnu** [comment]
@zerothabhishek Can we discuss this?

**Comment by bravegnu** [comment]
@zerothabhishek Can you please update the Devsprint CFP with the following text?

PyCon India is a place for developers from across the country (and beyond) to get together and celebrate Python. But what good is a PyCon without getting your hands dirty writing some code? Hence, for all Open Source enthusiasts out there, the PyCon India team is happy to announce Devsprints @ PyCon India 2019.

During Devsprints, mentors/contributors of OSS projects guide participants through the end-to-end process of OSS contribution, right from setting up build environments, to developing and testing code, to submitting patches for bugs. If you are stuck, mentors are all available to help you figure out issues and get you back up and running! From past experiences, we’ve seen a lot of people start off contributing to OSS through Devsprints and later go on to become regular contributors to various projects across the web.

If you are a contributor or have been involved in maintenance of any Open source project, please come forward and add a project. This project can be any interesting Open source project which is based on Python. Ideally, you should have a history with the project through previous code commits. Your responsibility will be to help your team set up their development environment, list out beginner friendly bugs, and guide them on any problems they face during the event.

**Any maintainer is welcome to add a project. There will be no shortlisting of projects. We are using the CFP platform to make it easier to manage and keep the projects at one place.**

### Date & Venue

  * Date: 14th & 15th October
  * Venue: IITM Research Park

**Comment by zerothabhishek** [comment]
Done
