### ISSUE TITLE
Poster Presentation Promotion

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#127]
![poster_guide](https://user-images.githubusercontent.com/1171852/60765172-acc9b080-a0b3-11e9-80a9-6ba48946a41a.png)

**Comment by bravegnu** [comment]
@rajkumartreads Please find my comments below:

  * The logo outlines in the background needs to be changed, they are the older versions, which were not approved by PSF. We are supposed to use the standard Python logo outline.

  * "Making an awesome poster presentation proposal" can be changed to "Making an awesome poster presentation".
  
  * "The Concept" could be rephrased as "The Topic"
  * "Get a simple Python project" is a little vague. I would probably put it as follows
    - Your project that you are really passionate about.
    - An interesting library / framework that you has made your life easier
    - An idea that you would like to share with others

  * The poster should be preferably an A0 sized poster, to make best use of the available space.

  * Also the font for the body text can be a different from the title text. Luxa does not work well as body text font.

  * Also we might get some extension on the deadline. Will keep you posted on that.

  * The microTalk -> The Micro Talk

**Comment by rajkumartreads** [comment]
@bravegnu Kindly find the draft 2.

![poster_guide_2](https://user-images.githubusercontent.com/4427534/61059361-8179f500-a416-11e9-9d06-c3b7ee7a1b2d.jpg)

**Comment by bravegnu** [comment]
Looks good @rajkumartreads! A few suggestions:

  * Use a sans serif font.
  * The title "Making an awesome poster presentation", needs to be made larger / prominent.

**Comment by rajkumartreads** [comment]
@bravegnu the draft 3.

![poster_guide_3](https://user-images.githubusercontent.com/4427534/61100939-a194cd00-a485-11e9-8414-20deb306b8b5.jpg)

**Comment by rajkumartreads** [comment]
Draft 4. Updated last date.

![poster_guide_4](https://user-images.githubusercontent.com/4427534/61348571-ca9ad080-a87e-11e9-8338-e86c20659028.jpg)
