### ISSUE TITLE
Present a Poster

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#131]
Subject: Present a Poster at PyCon India

Hi {Name}
{Add-Your-Context-Here}

As announced earlier, the posters are yet another way of participating in PyCon India 2019, which is happening on Oct 12-15, at Chennai. There are two different poster types, you can present at PyCon India.

  1. Technical Posters - for presenting projects and insights on various topics
  2. Community Posters - for user groups / meetup groups to promote their work

Here are few good reasons to present a poster:

1. Posters offer the opportunity to **engage with attendees** interested in the same subject and application as yourself. You might strike up a conversation with someone about your poster that may lead to future collaborations or even a job offer!

2. If you are new to conferences, or if you are intimidated about doing a talk in front of huge audience, posters are for you. Posters are a **great way to test the waters**, and can be stepping stone for your next talk at a conference.

3. The **entire conference attendees is available** during the poster session, as there are no other tracks scheduled in parallel. This makes it better than the talk sessions, where there are multiple concurrent tracks, and attendees can only attend one of them.

4. A poster presentation is a good way to disseminate your work, particularly if your **topic or project falls within a narrow field of specialization**. It also gives you the opportunity to actively engage with others during the conference in a way that networking alone does not, since by its very nature the poster defines the topic of conversation.

5. Another good reason to present a poster is that you can expect to receive compliments on your work and critiques that can help you in the future. An insightful, **impartial discussion of your work by a peer** can often provide ideas for improving your work downstream.

In short, poster presentations provide value, both for attendees who discuss your poster content with you, and for yourself because of the opportunities highlighted above. If this has got you interested, head to https://in.pycon.org/cfp/posters-2019/proposals/ for more details and to submit a poster proposal.

For more details about PyCon India, visit https://in.pycon.org/

Regards,
{your-name}
PyCon India 2019 Team

Credits: Partly based on https://people.clas.ufl.edu/oppenhe/2014/06/09/7-reasons-why-you-should-present-posters-at-a-conference/

**Comment by bravegnu** [comment]
How about presenting a poster at PyCon India? Here are a few good reasons to do so. Submit your proposal at https://in.pycon.org/cfp/posters-2019/proposals/

#Python #PyConIndia2019

![why-poster](https://user-images.githubusercontent.com/1171852/61681154-f2c87a80-ad29-11e9-806c-624a1f67a72e.jpg)

**Comment by bravegnu** [comment]
@gnurenga @rajkumartreads @abhishekmishragithub Just wanted to remind you about this. Please post to your contacts and update the sponsorship spreadsheet.

**Comment by abhishekmishragithub** [comment]
@bravegnu can you put that community poster presentation content here ?

**Comment by bravegnu** [comment]
@abhishekmishragithub Not sure what else you are looking for.

**Comment by abhishekmishragithub** [comment]
> @abhishekmishragithub Not sure what else you are looking for.

Please ignore.
