### ISSUE TITLE
Devsprint CFP is Open!

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#132]
CFP for devsprints is open! Submit your proposal at https://in.pycon.org/cfp/devsprint-2019/proposals/

#Python #PyConIndia2019

![devsprint-cfp](https://user-images.githubusercontent.com/1171852/61763307-94b39a00-adf2-11e9-8341-0602621edd24.png)

**Comment by anujaagarwal** [comment]
@bravegnu, I am taking over this task.

**Comment by bravegnu** [comment]
Hi @anujaagarwal This task is done. If you are interested you can look into #137
