### ISSUE TITLE
Add keynote speaker Jake Vanderplas

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#134]
We need to do the following for the next keynote speaker:

  1. Add a photo and title to front page 
  2. Create a blog post
  3. Create social media post for Jake Vanderplas

Title: Astronomer by Training; Author of Python Data Science Handbook; Developer at Google.

Photo: http://vanderplas.com/photos.html

Speaker Bio:

Jake VanderPlas is a long-time user and contributor to the Python data science ecosystem, and author of the Python Data Science Handbook. An astronomer by training, he currently works as a software engineer at Google in Seattle, WA. Recently, his efforts have been focused on data visualization tools, particularly the Altair and Vega-Lite libraries.

**Comment by bravegnu** [comment]
@astronomersiva Can you take this up?

**Comment by astronomersiva** [comment]
Sure

**Comment by bravegnu** [comment]
<hr/>

![keynote-speaker](https://user-images.githubusercontent.com/1171852/62009137-6844a880-b179-11e9-8d13-83e792e9926a.png)

We are happy to announce that Jake VanderPlas @jakevdp is a keynote speaker for PyCon India 2019! https://in.pycon.org/blog/2019/announcing-keynote-speaker-for-pycon-india-2019-jakevdp.html

#Python #PyConIndia2019
<hr/>
Notes: Please ensure that the URL is working before posting the tweet.
