### ISSUE TITLE
Workshop Tickets Announcement Poster

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#137]
We need a social media poster to announce "Workshop and Devsprint Tickets are Open!". @astronomersiva Can you get this done with the design team?

**Comment by bravegnu** [comment]
Workshop and devsprint tickets are open! The list of workshops is available from https://in.pycon.org/blog/2019/announcing-workshops.html

Book your tickets at https://www.townscript.com/e/pycon-india-2019/booking

#Python #PyConIndia2019

![workshop-open](https://user-images.githubusercontent.com/1171852/62410549-93f5e180-b604-11e9-9457-21310e7ead7c.png)

**Comment by anujaagarwal** [comment]
Can I take over this task? Do I have to tweet
the above poster @bravegnu?
Because poster is already designed.
