### ISSUE TITLE
Identify and book caterers for the conference

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#14]
We need identify and book caterers for the event, to provide Lunch on
Day 1 and Day 2 of the conference.

**Comment by abhishekmishragithub** [comment]
@bravegnu what about PySangamam cateres ?

**Comment by bravegnu** [comment]
We have a little more budget here, we can go for a different caterer. Also we will be better off choosing an empaneled caterer from http://www.chennaitradecentre.org/emresturant.html
