### ISSUE TITLE
Social Media Announcement for Poster Guide

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#142]
The What, Why and How of presenting posters at PyCon India 2019, at https://in.pycon.org/blog/2019/a-lucent-guide-to-poster-presentation.html

#Python #PyConIndia2019

![pysangamam_2018_3](https://user-images.githubusercontent.com/1171852/62829037-4d127800-bc12-11e9-8161-8d11e4c49d22.jpg)
![pysangamam_2018_2](https://user-images.githubusercontent.com/1171852/62829038-4dab0e80-bc12-11e9-9a16-2f36e0abf258.jpg)
![pysangamam_2018_1](https://user-images.githubusercontent.com/1171852/62829039-4dab0e80-bc12-11e9-9cce-3825fa0ce0a0.jpg)

**Comment by anujaagarwal** [comment]
@bravegnu, Can I take this work? Do I have to tweet from personal account or from PyCon account?
