### ISSUE TITLE
Adding Map Diagrams to 'Reaching the Venues' page in website

### ISSUE THREAD

**Issue by rajkumartreads** [pythonindia/inpycon2019-tasks#143]
![reaching_venues_distance_map](https://user-images.githubusercontent.com/4427534/62845825-de541e00-bce8-11e9-9646-2444fffcd2f6.png)
![reaching_venues_map_airport](https://user-images.githubusercontent.com/4427534/62845831-ea3fe000-bce8-11e9-9993-8b837b9efe84.png)
![reaching_venues_map_central](https://user-images.githubusercontent.com/4427534/62845833-f461de80-bce8-11e9-8a40-40d1a5e2f0a7.png)
![reaching_venues_map_cmbt](https://user-images.githubusercontent.com/4427534/62845836-fd52b000-bce8-11e9-8b5b-5b8780020ceb.png)

**Comment by rajkumartreads** [comment]
@gnurenga, sharing the images. You may use this in the website.

**Comment by gnurenga** [comment]
Will See how to add the images in to md file and send a pull request
