### ISSUE TITLE
Workshop posters for Social Media promotion

### ISSUE THREAD

**Issue by rajkumartreads** [pythonindia/inpycon2019-tasks#145]
![1_docker](https://user-images.githubusercontent.com/4427534/63161337-7f224080-c03d-11e9-8efd-33055789a20e.png)
![2_tornado](https://user-images.githubusercontent.com/4427534/63161347-88aba880-c03d-11e9-81c2-82aa264f1150.png)
![3_postgis](https://user-images.githubusercontent.com/4427534/63161361-906b4d00-c03d-11e9-9119-810253b61fc5.png)
![4_nlp](https://user-images.githubusercontent.com/4427534/63161367-94976a80-c03d-11e9-809e-c51905fc9333.png)
![5_ml_performance](https://user-images.githubusercontent.com/4427534/63161373-99f4b500-c03d-11e9-97e9-8ad7f34ca3b3.png)
![6_pgmpy](https://user-images.githubusercontent.com/4427534/63161380-9e20d280-c03d-11e9-93d3-a0aedede98cb.png)
![7_async](https://user-images.githubusercontent.com/4427534/63161386-a1b45980-c03d-11e9-9b43-3348d39466bb.png)
![8_openfaas](https://user-images.githubusercontent.com/4427534/63161397-a711a400-c03d-11e9-8e66-fa0ff8e781b8.png)
![9_3d](https://user-images.githubusercontent.com/4427534/63161404-aa0c9480-c03d-11e9-9646-18ac51e40181.png)
![10_pyro](https://user-images.githubusercontent.com/4427534/63161409-ad078500-c03d-11e9-9170-fa592b5afaf7.png)
![11_spark](https://user-images.githubusercontent.com/4427534/63161419-b264cf80-c03d-11e9-9bc3-87fed5edbcf0.png)
![12_edge](https://user-images.githubusercontent.com/4427534/63161429-b5f85680-c03d-11e9-9eec-7466e19c7a72.png)

**Comment by rajkumartreads** [comment]
@gnurenga, you can use it in SM posts.

**Comment by bravegnu** [comment]
Attend focused hands-on workshops, by experts, at #PyConIndia2019. The workshops happen in parallel. You can attend one of the following morning workshops.

<hr/>

Demystifying @Docker for Devs by Sanchit Balchandani @inovizz and Mahendra Yadav @userimack

Details: https://in.pycon.org/cfp/workshops-2019/proposals/demystifying-docker-for-devs~e9WPb/ 

Tickets: https://in.pycon.org/2019/#tickets

![1_docker](https://user-images.githubusercontent.com/4427534/63161337-7f224080-c03d-11e9-8efd-33055789a20e.png)

<hr/>

Building, testing and profiling efficient micro-services using Tornado by Satish Chandra Gupta @scgupta

Details: https://in.pycon.org/cfp/workshops-2019/proposals/building-testing-and-profiling-efficient-micro-services-using-tornado~e9vxa/

Tickets: https://in.pycon.org/2019/#tickets

![2_tornado](https://user-images.githubusercontent.com/4427534/63161347-88aba880-c03d-11e9-81c2-82aa264f1150.png)

<hr/>

Geospatial API with Python and @PostGIS by Nick Doiron @mapmeld

Details: https://in.pycon.org/cfp/workshops-2019/proposals/geospatial-api-with-python-and-postgis~bmm0b/

Tickets: https://in.pycon.org/2019/#tickets

![3_postgis](https://user-images.githubusercontent.com/4427534/63161361-906b4d00-c03d-11e9-9119-810253b61fc5.png)

<hr/>

Demystifying Natural Language Processing using Python (Scikit-Learn/ Keras) by Vaibhav Srivastav @vaibhavsriv10

Details: https://in.pycon.org/cfp/workshops-2019/proposals/demystifying-natural-language-processing-using-python-scikit-learn-keras~eg46a/

Tickets: https://in.pycon.org/2019/#tickets

![4_nlp](https://user-images.githubusercontent.com/4427534/63161367-94976a80-c03d-11e9-809e-c51905fc9333.png)

<hr/>

Advance ML- On Improving Performance of Machine Learning Models by Optimizing Hyper-parameters by Tanay Agrawal @agrawal_tanay and Anubhav Kesari

Details: https://in.pycon.org/cfp/workshops-2019/proposals/advance-ml-on-improving-performance-of-machine-learning-models-by-optimizing-hyper-parameters~bYPpa/ 

Tickets: https://in.pycon.org/2019/#tickets

![5_ml_performance](https://user-images.githubusercontent.com/4427534/63161373-99f4b500-c03d-11e9-97e9-8ad7f34ca3b3.png)

<hr/>

Global macro trading strategy using PGM (pgmpy package) by Abinash Panda and Usha Rengaraju

Details: https://in.pycon.org/cfp/workshops-2019/proposals/global-macro-trading-strategy-using-pgmpgmpy-package~azJ8a/

Tickets: https://in.pycon.org/2019/#tickets

![6_pgmpy](https://user-images.githubusercontent.com/4427534/63161380-9e20d280-c03d-11e9-93d3-a0aedede98cb.png)

**Comment by bravegnu** [comment]
Here are the afternoon workshops for #PyConIndia2019. You can attend one of the following.

<hr/>

Build your Own Async by David Beazley @dabeaz

Details: https://in.pycon.org/2019/workshop-build-your-own-async.html

Tickets: https://in.pycon.org/2019/#tickets

![7_async](https://user-images.githubusercontent.com/4427534/63161386-a1b45980-c03d-11e9-9b43-3348d39466bb.png)

<hr/>

Serverless with @OpenFaaS and Python by Vivek Kumar Singh 

Details: https://in.pycon.org/cfp/workshops-2019/proposals/serverless-with-openfaas-and-python~aAkBd/

Tickets: https://in.pycon.org/2019/#tickets

![8_openfaas](https://user-images.githubusercontent.com/4427534/63161397-a711a400-c03d-11e9-8e66-fa0ff8e781b8.png)
<hr/>

Creating 3D Environments by Ashish Dantu and Team. 

Details: https://in.pycon.org/cfp/workshops-2019/proposals/creating-3d-environments~dNvKd/

Tickets: https://in.pycon.org/2019/#tickets

![9_3d](https://user-images.githubusercontent.com/4427534/63161404-aa0c9480-c03d-11e9-9646-18ac51e40181.png)
<hr/>

Pyro Demystified : Bayesian Deep Learning by Suriyadeepan @iamdionysus

Details: https://in.pycon.org/cfp/workshops-2019/proposals/pyro-demystified-bayesian-deep-learning~en4lb/

Tickets: https://in.pycon.org/2019/#tickets

![10_pyro](https://user-images.githubusercontent.com/4427534/63161409-ad078500-c03d-11e9-9170-fa592b5afaf7.png)
<hr/>

Distributed Machine learning in python using @ApacheSpark by Satwik Kansa @satwikkansal

Details: https://in.pycon.org/cfp/workshops-2019/proposals/distributed-machine-learning-in-python-using-apache-spark~e5vBa/

Tickets: https://in.pycon.org/2019/#tickets

![11_spark](https://user-images.githubusercontent.com/4427534/63161419-b264cf80-c03d-11e9-9bc3-87fed5edbcf0.png)
<hr/>

Deploying Machine Learning Models at the Edge by Ankit Mahato

Details: https://in.pycon.org/cfp/workshops-2019/proposals/deploying-machine-learning-models-at-the-edge~eVq1d/

Tickets: https://in.pycon.org/2019/#tickets

![12_edge](https://user-images.githubusercontent.com/4427534/63161429-b5f85680-c03d-11e9-9eec-7466e19c7a72.png)
