### ISSUE TITLE
Hall allocation for the 3 tracks

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#15]
The conference will have 3 talk tracks. The CTC has 2 1000 seater
halls, 1 service lobby and 1 VIP lobby. There are two possibilites.

Divide one of the 1000 seater halls into two tracks, using a temporary
partition. The biggest challenge with this approach is to prevent
cross talk across the partition.

The second approach is to use the VIP lobby as a talk track. The VIP
lobby needs to be evaluated for suitability for such use.

**Comment by raghavendrasv** [comment]
@bravegnu the 2 1000 seater halls are quite big. CTC may help in dividing using the partition.

my opinion, VIP lobby may get congested, we can plan to divide one hall, the cross talk can be reduced by the placement of speakers, once again CTC could be helping in this.

**Comment by bravegnu** [comment]
@vrsthe1 The partitioning is all left out to us. CTC does not provide any support beyond providing the space.
