### ISSUE TITLE
Promote Python Express

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#151]
Promote Python Express among trainers for registering themselves as a tutor. And promote Python Express among schools and acolleges to register a workshop request.

**Comment by amrrs** [comment]
@bravegnu Sorry to jump in, Just curious to know what's `Python Express`, Any links you could help me with?

Before posting this, DDGed - no result

**Comment by amrrs** [comment]
Poor me got it here https://github.com/pythonindia/inpycon2019-tasks/issues/144
