### ISSUE TITLE
Poster printing service

### ISSUE THREAD

**Issue by nishadhka** [pythonindia/inpycon2019-tasks#159]
Transportation/packaging is to be the main reason to go for poster print in expensive materials such as in Matte/glossy photo paper or high grade vinyl. Local poster print service could avoid this with printing in normal paper on much cheaper rate. Besides, a single point poster print would be advantageous in maintaining quality.

**Comment by bravegnu** [comment]
Thanks for the suggestion Nishadh. Let me check if this can be done by the organizing team.
