### ISSUE TITLE
Ticket sales closing

### ISSUE THREAD

**Issue by abhishekmishragithub** [pythonindia/inpycon2019-tasks#161]
The Ticket sales for PyCon India 2019 will close at 11:59 pm on 30th of September. This includes purchasing of new tickets, transfer of purchased tickets and cancellation requests. 
If you are not able to attend the conference, please contact tickets@in.pycon.org. We have people in waiting list who are willing to buy a conference ticket.

**Comment by bravegnu** [comment]
If you are not able to attend the conference, please contact tickets@in.pycon.org, before 30th September. We have people in waiting list who are willing to buy a conference ticket.

**Comment by gok03** [comment]
The Ticket sales for PyCon India 2019 will close at 11:59 pm on 30th of September. This includes purchasing of new tickets, transfer of purchased tickets and cancellation requests.
If you are not able to attend the conference, please contact tickets@in.pycon.org, before 30th September. We have people in waiting list who are willing to buy a conference ticket.

**Comment by bravegnu** [comment]
If you have a ticket and you are not able to attend ...
