### ISSUE TITLE
Posters Announcement

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#164]
The list of selected posters, both technical and community, is available from https://in.pycon.org/cfp/posters-2019/proposals/#proposals Congratulations to the presenters!

#Python #PyConIndia2019

**Comment by amrrs** [comment]
@bravegnu I submitted the poster pdf but due to some issues the submission didn't go through and I submitted again at 5:10 pm (which is after the 5:00 pm) deadline. Is it possible that my pdf is considered for printing? 

Thnks!

**Comment by bravegnu** [comment]
@amrrs Please submit your request for poster printing at https://forms.gle/t2LQ39b51FeFXPLE7

**Comment by bravegnu** [comment]
@amrrs OK, got it. Will handle it.

**Comment by amrrs** [comment]
@bravegnu Really appreciate it!
