### ISSUE TITLE
Bags for conference attendees

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#18]
We will need to provide branded bags for the attendees. The bags will
contain the goodies, sponsor brochures, etc. We have a suggestion in
this regard: http://paalaguttapalle.com

**Comment by abhishekmishragithub** [comment]
@bravegnu can we choose one vendor who does tote bag printing, t-shirt and other swags.
I highly recommend InkMonk (https://inkmonk.com)

For bags have a look at this :  https://inkmonk.com/categories/cotton-carry-bags/customizable-products/large-kraft-paper-bag-printing

**Comment by bravegnu** [comment]
There is a social aspect to Paalaguttapalle, please read http://paalaguttapalle.com//index.php?route=extension/d_blog_module/post&post_id=11

**Comment by abhishekmishragithub** [comment]
> There is a social aspect to Paalaguttapalle, please read http://paalaguttapalle.com//index.php?route=extension/d_blog_module/post&post_id=11

Yeah, gotcha !!
