### ISSUE TITLE
Call for volunteers for Promotion Workgroup

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#2]
- [x] Bangalore

- [x] Chennai

- [x] Delhi

- [ ] Hyderabad

- [ ] Kerala

- [ ] Mumbai

- [ ] Mysore

- [ ] Gujarat

- [ ] Pune

- [x] Jaipur

**Comment by bravegnu** [comment]
@gnurenga Lets first send announcement mail for PyCon India 2019. And then lets send call for volunteers.

**Comment by abhishekmishragithub** [comment]
was there any form ?

**Comment by abhishekmishragithub** [comment]
Please let me know if anything needs to be changed in updated page. (I have added some more groups for Chennai region)

**Comment by gnurenga** [comment]
Thank you @abhishekmishragithub for your valuable contribution we will get in touch with your for promotions.

**Comment by gnurenga** [comment]
> @gnurenga Lets first send announcement mail for PyCon India 2019. And then lets send call for volunteers.

Sure @bravegnu

**Comment by bravegnu** [comment]
Separate ticket #3 created for announcement mail.

**Comment by raghavendrasv** [comment]
Hi guys, 
I am newbie to programing and python, love to help. I live in jaipur.

**Comment by gnurenga** [comment]
@vrsthe1 you can add your name under Jaipur in wiki page. And you can start working on #3  issue. Also follow the guidelines for adding you as volunteer for Jaipur. 
## Steps

- Go to wiki
- Click on Promotions
- Read the Guidelines.
- Add your name against the state you like to help us in promotion

**Comment by gnurenga** [comment]
@vrsthe1  If you are a student can you add your college name ? To notify your college about the conference.  @shivank98 and @vrsthe1  please sync together since you both are from same city

**Comment by raghavendrasv** [comment]
> @vrsthe1 If you are a student can you add your college name ? To notify your college about the conference. @Shivank98 and @vrsthe1 please sync together since you both are from same city

@gnurenga, I am working, not IT. May be should I take up responsibility to send to other groups or mailing lists??
yes will sync with @Shivank98.

**Comment by gnurenga** [comment]
> > @vrsthe1 If you are a student can you add your college name ? To notify your college about the conference. @Shivank98 and @vrsthe1 please sync together since you both are from same city
> 
> @gnurenga, I am working, not IT. May be should I take up responsibility to send to other groups or mailing lists??

Even you can post to the group as @Shivank98 mentioned in wiki and also you can add other groups which is not mentioned. Make sure not to duplicate posting.

> yes will sync with @Shivank98.

Yes please. It will avoid duplicate stuff :100:
