### ISSUE TITLE
Identify T-Shirt vendor

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#26]
Since logo is out, we need to start identifying the vendor get some tshirt design ready.

**Comment by bravegnu** [comment]
T-Shirt design will be done by Webchirpy.

**Comment by babuenir** [comment]
Referring "House of Uniforms and Fashion Clothing". Vendor of PySangamam T-Shirt

**Comment by abhishekmishragithub** [comment]
Go with InkMonk they have very good quality of print discounts for big orders. I have a direct contact in InkMonk.

**Comment by py-ranoid** [comment]
+1 for InkMonk. They're a Chennai-based startup. I can get in touch with their CEO.

**Comment by bravegnu** [comment]
We can get a quote a sample T-Shirt from the vendors, before deciding on one.

**Comment by arunedwin-imaginea** [comment]
SKR Garments
Tirupur 
+91 9952118456

Item Name | Price
Round neck  Non-wash   Size  XS to .  XXL   | Rs 170.00Rs 150.00 above 1000 pcs
Collor  T-shirt  Bio-wash  240 gsm Size  M  to XXL  | Rs 290.00Rs 270.00 above 500 pcs

They would give us a sample t-shirt for the material feel. To whom should we send the sample T-shirts.

**Comment by bravegnu** [comment]
@arunedwin-imaginea Can you please co-ordinate with @babuenir @abhishekmishragithub and get the quote from other vendors as well?

**Comment by arunedwin-imaginea** [comment]
> @py-ranoid   +1 for InkMonk. They're a Chennai-based startup. I can get in touch with their CEO. 
Hi Vishal, If you know the CEO in person, Please talk to him and get a quote on the t-shirts. And share it here.

**Comment by abhishekmishragithub** [comment]
@bravegnu  i spoke with InkMonk , they can give discounts on bulk order. We need to mail T-shirt design and depending on that they will get back to us.
the average t-shirt price is - 195 Rupee (Checked on website)

**Comment by bravegnu** [comment]
@babuenir Can you please get a few samples from the vendor?

**Comment by bravegnu** [comment]
> @babuenir Can you please get a few samples from the vendor?

@babuenir Just wanted to remind you about this. Can we get a few samples, in different thickness and print styles.
