### ISSUE TITLE
Try and recover access to LinkedIn company page

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#27]
There is a LinkedIn company page for PyCon India
https://www.linkedin.com/company/pycon-india/people/ We can try and
see if we can recover this account.

**Comment by abhishekmishragithub** [comment]
@bravegnu who was handling for last years PyCon ? We already asked this in mailing list but we didn't get positive response. Probably we should contact previous years team.

**Comment by bravegnu** [comment]
I don't think the last year team had access to it either.

**Comment by py-ranoid** [comment]
Can we create another LinkedIn page ?

**Comment by bravegnu** [comment]
There is a LinkedIn group https://www.linkedin.com/groups/3203762/

**Comment by bravegnu** [comment]
Did not materialize let's drop this.
