### ISSUE TITLE
Create AWS account for backups

### ISSUE THREAD

**Issue by zerothabhishek** [pythonindia/inpycon2019-tasks#28]
We need Aws-S3 to backup the Junction Db. Can be used for other backups as well

**Comment by abhishekmishragithub** [comment]
personal account or we need to create for pycon ?

**Comment by zerothabhishek** [comment]
Ping @bravegnu 
@abhishekmishragithub we need an account with PSSI or Afrost as the owner, since we are going to store personal/private information. A personal account is not appropriate for the purpose.

**Comment by abhishekmishragithub** [comment]
@zerothabhishek i'll get in touch with Vijay

**Comment by bravegnu** [comment]
Would a Dropbox account work?

**Comment by zerothabhishek** [comment]
(Sorry for the late response). Dropbox may not be appropriate. Since this is backup data, it will occupy a big chunk of space on Dropbox. It will also get synced across multiple devices, which is not desirable.

**Comment by bravegnu** [comment]
> (Sorry for the late response). Dropbox may not be appropriate. Since this is backup data, it will occupy a big chunk of space on Dropbox. It will also get synced across multiple devices, which is not desirable.

What is the expected size of the data. Also Dropbox can be uploaded through the web interface.
