### ISSUE TITLE
Decide on which approaches we will do to increase participation of women Pythonistas

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019-tasks#29]
There are many ideas put forward by Team PyCon and Pyladies Chennai for creating awareness and inspiring more participation. We need to estimate the amount of effort is required and which we should prioritize.

**Comment by zerothabhishek** [comment]
Relevant: https://github.com/sharmi/inpycon2019-tasks/blob/master/Diversity/PyLadies.md

**Comment by niharikakrishnan** [comment]
Can we fix a meeting or create a workgroup in this week to discuss these ideas? We would also need support from CFP/Promotion/Sponsorship/Logistics to help finalize on which of these ideas can actually be implemented.

**Comment by bravegnu** [comment]
We can have a regular weekly meeting on Saturday, to discuss about diversity. Do let me know if this works for you.

**Comment by niharikakrishnan** [comment]
> We can have a regular weekly meeting on Saturday, to discuss about diversity. Do let me know if this works for you.

Sure, Saturday is fine with me. Thank you!

**Comment by sharmi** [comment]
Child care has been taken off as there has not been much demand in the past years. Group discount was considered wrong incentive as companies have the money to sponsor if they set their hearts to it. Other than that, all the other options are viable and on the plan.

The consensus on sponsored giveaways and goodies was that, as free, they tend to lose perceived value and are not actually used, yet we can pursue that if the team is interested. JetBrains has a structured program for meetups and workgroups so working with them should be easy. We could mail them about our project and see if we can work out something promising. We can try other options too.

https://www.jetbrains.com/community/support/#section=communities
