### ISSUE TITLE
PyCon India 2019 Announcement

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#3]
The following announcement template is for Python User Groups, where people already familiar with PyCon India.

``````
Hi Everyone,
PyCon India, India's premier conference on using and developing
the Python programming language, is happening in Chennai this
year, from October 12 to 15, 2019! Mark your calendars now!

We are accepting sponsorship and CFP also open now. We will be opening tickets soon. 
Don't want to miss an update from us? Subscribe for updates at
https://in.pycon.org/

Regards,
<Your Name>
On Behalf of
PyCon India Organizing Team
``````

The following announcement template is for the other user groups and private mailing lists, where people are not familiar with PyCon India.

``````
Hi Everyone,
PyCon India, is happening in Chennai this year, from October 12
to 15, 2019!

For the uninitiated, PyCon India is India's premier conference on
using and developing the Python programming language. This year's
conference is a 4 day event, with keynote speakers from the
international Python community, 3 parallel talk tracks, 4
parallel workshop tracks, a poster session, lightning talks
session and a lot more! About 1200 Pythonistas from all over
India are expected to participate in the event.

We are accepting sponsorship and CFP also open now. We will be opening tickets soon. 
 If you don't want to miss an update from us, subscribe for updates at
https://in.pycon.org/

Regards,
<Your Name>
On Behalf of
PyCon India Organizing Team
``````

**Comment by bravegnu** [comment]
Twitter and social media announcement template for PyCon India owned groups only. For other groups consider using the email template, that includes the subscribe link.

``````
Mark your calendars!

PyCon India, India's premier conference on using and developing the Python programming language, is happening in Chennai this year, from October 12 to 15, 2019! http://in.pycon.org/

#Python #PyConIndia2019
``````

**Comment by bravegnu** [comment]
We will need to post to the following usergroups. The template will have to be tweaked for each category.

- [x] PySangamam
- [ ] PyCon India 2018 Attendees
- [x] BangPypers
- [x] Chennaipy
- [x] Pyladies Chennai
- [x] KovaiPy
- [ ] KolPy
- [ ] DPUG (DehraDun Python Users Group)
- [ ] PyGuj
- [x] KPUG (Kerala Python Users Group)
- [ ] Kochi Python Users Group
- [x] PyDelhi
- [ ] MumPy
- [x] Pune Python Users Group
- [ ] IITD Lug
- [x] Hyderabad Python Users Group
- [ ] Python Developers Baroda
- [ ] Pyladies Bangalore
- [ ] Django India
- [ ] Bhubaneshwar Pythonists
- [ ] APPy
- [x] ILUGC
- [x] Puduvailug
- [x] ILUG-BOM
- [x] PyJaipur

**Comment by sayanchowdhury** [comment]
We are missing BangPypers here. Also, which one is DPUG?

**Comment by sayanchowdhury** [comment]
> We are missing BangPypers here. Also, which one is DPUG?

I see DPUG is the Dehradun Python Users' Group.

**Comment by bravegnu** [comment]
> > We are missing BangPypers here. Also, which one is DPUG?
> 
> I see DPUG is the Dehradun Python Users' Group.

The list has been updated for clarity. And BangPypers has been added as well.

**Comment by sayanchowdhury** [comment]
This is another list that was around PyCon India 2014 for publicity[1]. Check this if we find some more active mailing list from the link

[1] https://github.com/pythonindia/pyconindia/wiki/Publicity2014#mailing-lists

**Comment by abhishekmishragithub** [comment]
Please add Pyladies Chennai

**Comment by stylesen** [comment]
@abhishekmishragithub Added "Pyladies Chennai".

**Comment by stylesen** [comment]
> Please add Pyladies Chennai

Done.

**Comment by gnurenga** [comment]
@abhishekmishragithub @abhishekmishragithub @aaronstone007 @shivank98 Can you send announcement mail to the group you are taking care. Update the check list once you done.

**Comment by gnurenga** [comment]
## Volunteer update once sending the promotion mail
Kindly use the promotion template. Any doubts comment here
- [x] @gnurenga
- [x] @abhishekmishragithub
- [x] @aaronstone007
- [x] @shivank98
- [ ]  @TanviKumar
- [ ]  @Dhanya-Abhirami
- [ ] @niharikakrishnan

**Comment by bravegnu** [comment]
I have posted the announcement to ILUGC and Puduvailug.

**Comment by abhishekmishragithub** [comment]
> @abhishekmishragithub @abhishekmishragithub @aaronstone007 @Shivank98 Can you send announcement mail to the group you are taking care. Update the check list once you done.

Yes , its on going.
once done i'll update

**Comment by bravegnu** [comment]
Posted to Pune and Hyderabad Python User Groups.

**Comment by bravegnu** [comment]
Hi @TanviKumar, can you post the above template to the mailing lists in NITT.

**Comment by bravegnu** [comment]
Hi @Dhanya-Abhirami, can you post the above template to the mailing lists in VIT.

**Comment by abhishekmishragithub** [comment]
Posted in GCDC Chennai, GDG Chennai, XMonkeys360 and Fn-Geeks Chennai.
Other groups are on the way. I am simply posting in their group , instead putting the promotion slides in events as well !

**Comment by bravegnu** [comment]
Hi @abhishekmishragithub, We have two templates now. For non Python User Groups, please use the more detailed template.

**Comment by bravegnu** [comment]
@abhishekmishragithub does GDG Chennai have a mailing list?

**Comment by abhishekmishragithub** [comment]
> @abhishekmishragithub does GDG Chennai have a mailing list?

@bravegnu GDG is not having any mailing list. Please let me know what needs to be done, i can go ahead with that. and let me know if PyCon team need community partners as well. i can definitely do that.

**Comment by abhishekmishragithub** [comment]
> Hi @abhishekmishragithub, We have two templates now. For non Python User Groups, please use the more detailed template.

Sure, i'll use latest one. Thanks !

**Comment by bravegnu** [comment]
> > @abhishekmishragithub does GDG Chennai have a mailing list?
> 
> @bravegnu GDG is not having any mailing list. Please let me know what needs to be done, i can go ahead with that. and let me know if PyCon team need community partners as well. i can definitely do that.

I was wondering how you posted the announcement to GDG.

**Comment by abhishekmishragithub** [comment]
> > > @abhishekmishragithub does GDG Chennai have a mailing list?
> > 
> > 
> > @bravegnu GDG is not having any mailing list. Please let me know what needs to be done, i can go ahead with that. and let me know if PyCon team need community partners as well. i can definitely do that.
> 
> I was wondering how you posted the announcement to GDG.

I did using meetup page and during events we add announcement deck of PyCon India 2019; same for Google cloud community, they have Facebook group as well, so i did mention there as well.

**Comment by bravegnu** [comment]
> > > > @abhishekmishragithub does GDG Chennai have a mailing list?
> > > 
> > > 
> > > @bravegnu GDG is not having any mailing list. Please let me know what needs to be done, i can go ahead with that. and let me know if PyCon team need community partners as well. i can definitely do that.
> > 
> > 
> > I was wondering how you posted the announcement to GDG.
> 
> I did using meetup page and during events we add announcement deck of PyCon India 2019; same for Google cloud community, they have Facebook group as well, so i did mention there as well.

OK, Got it!

**Comment by abhishekmishragithub** [comment]
@bravegnu i am co-coordinating with **MumPy** as well, their mailing list seems to have a silence from very long time. I'll update once i am done.

**Comment by abhishekmishragithub** [comment]
> ## Volunteer update once sending the promotion mail
> Kindly use the promotion template. Any doubts comment here
> 
> * [ ]  @gnurenga
> * [x]  @abhishekmishragithub
> * [ ]  @aaronstone007
> * [ ]  @Shivank98

@gnurenga Please mark my check-box as completed. I have successfully posted in all groups.
Let me know if could promote this in different colleges as well (I can do that).

**Comment by gnurenga** [comment]
> > ## Volunteer update once sending the promotion mail
> > Kindly use the promotion template. Any doubts comment here
> > 
> > * [ ]   @gnurenga
> > * [x]   @abhishekmishragithub
> > * [ ]   @aaronstone007
> > * [ ]   @Shivank98
> 
> @gnurenga Please mark my check-box as completed. I have successfully posted in all groups.
> Let me know if could promote this in different colleges as well (I can do that).

@abhishekmishragithub  Thank you abhisek i will mark the check box. Also next time you yourself can mark the check since it is volunteer effort. :+1:  score :100:

**Comment by abhishekmishragithub** [comment]
> > > ## Volunteer update once sending the promotion mail
> > > Kindly use the promotion template. Any doubts comment here
> > > 
> > > * [ ]    @gnurenga
> > > * [x]    @abhishekmishragithub
> > > * [ ]    @aaronstone007
> > > * [ ]    @Shivank98
> > 
> > 
> > @gnurenga Please mark my check-box as completed. I have successfully posted in all groups.
> > Let me know if could promote this in different colleges as well (I can do that).
> 
> @abhishekmishragithub Thank you abhisek i will mark the check box. Also next time you yourself can mark the check since it is volunteer effort.  score

@gnurenga sure, from next time i'll do it, sorry for inconvenience. :)

**Comment by shivankgtm** [comment]
@bravegnuI will send mail to the mailing list in a couple of days.

**Comment by aaronstone007** [comment]
> ## Volunteer update once sending the promotion mail
> Kindly use the promotion template. Any doubts comment here
> 
> * [ ]  @gnurenga
> * [x]  @abhishekmishragithub
> * [x]  @aaronstone007
> * [ ]  @Shivank98
> * [ ]   @TanviKumar
> * [ ]   @Dhanya-Abhirami


I've updated to my groups also since most are college groups, there is a question about registration costs and workshops.

**Comment by gnurenga** [comment]
> > ## Volunteer update once sending the promotion mail
> > Kindly use the promotion template. Any doubts comment here
> > 
> > * [ ]   @gnurenga
> > * [x]   @abhishekmishragithub
> > * [x]   @aaronstone007
> > * [ ]   @Shivank98
> > * [ ]    @TanviKumar
> > * [ ]    @Dhanya-Abhirami
> 
> I've updated to my groups also since most are college groups, there is a question about registration costs and workshops.

@aaronstone007 Thank you. You can convey them that we will notify once we open tickets for conference and workshop.

**Comment by shivankgtm** [comment]
@bravegnu, I have posted in PyJaipur mailing list. you can mark in checkboxes.

**Comment by abhishekmishragithub** [comment]
@bravegnu can you please add ILUG-BOM in list.
I have sent the announcement to mailing list of ILUG-BOM (gnu/linux user group of mumbai)

**Comment by abhishekmishragithub** [comment]
@bravegnu could you please add ILUG-BOM in the list.
I have sent the announcement to mailing list of ILUG-BOM

*Note : ILUG-BOM is gnu/linux user group of Mumbai

**Comment by gnurenga** [comment]
Hi @niharikakrishnan Can you post the above template mail within SRM ?

**Comment by niharikakrishnan** [comment]
> Hi @niharikakrishnan Can you post the above template mail within SRM ?

SRM clubs/teams do not have a concept of a mailing list. They mostly use FB pages where I could forward the above template. Is that alright?

**Comment by gnurenga** [comment]
> > Hi @niharikakrishnan Can you post the above template mail within SRM ?
> 
> SRM clubs/teams do not have a concept of a mailing list. They mostly use FB pages where I could forward the above template. Is that alright?

I guess it is fine to post the template in FB, @bravegnu Do you have any suggestion on posting same promotion mailing template as FB post.

**Comment by gnurenga** [comment]
@niharikakrishnan  you can post the template in FB. Before posting CFP, first post the

**Comment by gnurenga** [comment]
@niharikakrishnan  you can post the template to FB, no issues.
