### ISSUE TITLE
Identify and book hotel for keynote speakers

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#31]

**Comment by bravegnu** [comment]
Currently we are looking at Hilton or Le Royal Meridien.

**Comment by arunedwin-imaginea** [comment]
We can look for feathers hotel, I saw that close to Chennai trade center. It is a five-star property well.

**Comment by bravegnu** [comment]
Currently we are considering Hilton and Le Royal Meridien. We hope this will make it closer to both CTC and IITMRP.
