### ISSUE TITLE
Open CFP for posters

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#38]
The poster session is tentatively scheduled to be on the first day of
the conference. It will be a 1-hour session after lunch, and is
tentatively to be held at the Service lobby and the VIP lobby of the
venue. Poster presenters will be given a poster board where a A0 size
poster can be afixed. A desk will also be provided for people to place
their laptop for demonstrations.

The posters to be presented at the conference will be selected through
the CFP process.

**Comment by zerothabhishek** [comment]
I'll need some help with the copy for posters. If there's one from another/older conf, that too would be useful

**Comment by bravegnu** [comment]
Will this be helpful? https://us.pycon.org/2019/speaking/posters/

**Comment by zerothabhishek** [comment]
Yes that helps. Thanks
