### ISSUE TITLE
Cover Image for Twitter and Facebook 

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#4]

**Comment by bravegnu** [comment]
The logo design will be finalized by the beginning of next week. Let's wait for it.

**Comment by abhishekmishragithub** [comment]
@bravegnu the options for design and logo are same that you sent in mailing list, right ?

**Comment by abhishekmishragithub** [comment]
@gnurenga and @bravegnu let me know if we need any more graphic designers.

**Comment by bravegnu** [comment]
> @bravegnu the options for design and logo are same that you sent in mailing list, right ?

Yes

**Comment by gnurenga** [comment]
This can be closed since both FB and twitter are updated with 2019 logo and banners.
