### ISSUE TITLE
Weekly workgroup meeting schedule

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#40]
With the workgroups in place we would like to start weekly sync-up meeting (online) within the workgroup. Each workgroup can come up with a week day on which they can meet regularly:

  * CFP
  * Sponsorship
  * Logistics
  * Website / Design
  * Promotion

**Comment by gnurenga** [comment]
Working with the current team to schedule weekly meeting.

**Comment by gnurenga** [comment]
Promotion work group have decided to meet on every Friday 9:00 PM to 9:30 PM

**Comment by bravegnu** [comment]
We are moving the promotion workgroup meeting to Thursday between 9:00 PM and 9:30 PM.

**Comment by bravegnu** [comment]
@stylesen Can you please add the meeting schedule for the sponsorship workgroup?

**Comment by stylesen** [comment]
@bravegnu happens every week on Wednesday's at 8:30-9:00pm IST starting from 08-may-2019.

**Comment by bravegnu** [comment]
Schedule:

  * Monday: Core Team
  * Tuesday: Promotion
  * Wednesday: Sponsorship
  * Thursday: Diversity
