### ISSUE TITLE
Reaching out to institutions / companies for promotion

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#44]
* Companies in Chennai
  - Amazon
  - ThoughtWorks
  - PayPal
  - Bank of America
  - Freshworks
  - Comcast
  - Valeo
  - KLA
  - Tiger Analytics
  - Extreme Networks
  - Gigamon
  - OrangeScape
  - Aricent
  - Accenture
  - Pramati
  - Qube Cinemas
  - Poshmark
* NITs
  - NIT Puducherry
  - NIT Calicut
  - NIT Surathkal
  - NIT Goa
  - NIT Warangal
  - NIT Tadepalligudem
  - NIT Jaipur
* IITs
  - IIT Madras
  - IIT Tiruapti
  - IIT Goa
  - IIT Dharwad
  - IIT Hyderabad
  - IIT Palakkad
* IIITs
  - IIIT Kanchipuram
  - IIIT Sricity
  - IIIT Kottayam
  - IIIT Dharwad
  - IIIT Kurnool
  - IIIT Pune
* Other Colleges in Chennai
  - CEG
  - MIT
  - CMI

**Comment by bravegnu** [comment]
Let's keep this simple Regaraj. Let's just track the list of orgs that we want to establish contact with over here. Once we have a contact point we can add it to the Promotion wiki page.

**Comment by abhishekmishragithub** [comment]
Are we starting this ?

**Comment by bravegnu** [comment]
We will discuss this in tomorrow's weekly meeting.

**Comment by bravegnu** [comment]
Arulalan @arulalanv a researcher from MIT is willing to help us with promotion within MIT.

**Comment by Dhanya-Abhirami** [comment]
I can help out in reaching out to IIIT Sri City.

**Comment by bravegnu** [comment]
Reach out to folks at Aura Auro http://www.auraauro.com They even seem to be doing workshop on Django.

**Comment by bravegnu** [comment]
Rajkumar has met with NITT students has given them a brief of the event. He is also getting in touch with Bishop Heber College and IIIT Srirangam.

He is planning to reach out to Govt. College of Engineering in Theni.

**Comment by bravegnu** [comment]
Attended Women in Data Science meetup yesterday, where I got to meet the organizers, folks from H2O.ai and folks from Paypal who were providing space for the meetup. Will write a detailed report to the promotions workgroup.

I also got to meet a people from Pramati, HappyFox, Virtusa and Comcast, yesterday at the Chennaipy meetup. Will be getting in touch with them, shortly.

**Comment by sharmi** [comment]
I can help with promoting in CEG.

**Comment by gnurenga** [comment]
> Arulalan @arulalanv a researcher from MIT is willing to help us with promotion within MIT.

@arulalanv we have invited you to join Promotion work group, Please check your mail.

**Comment by bravegnu** [comment]
I have got a few contact in the companies listed above, will send them to you @gnurenga

**Comment by bravegnu** [comment]
We need to reach out to https://djangogirls.org/trivandrum/

**Comment by rajkumartreads** [comment]
To update, I'm reaching the following organizations:

**Colleges/Universities:**

NIT Trichy
IIIT Srirangam Trichy
IIM Trichy
Bishop Heber College Trichy
SASTRA Trichy
Bharathidasan University Trichy
Government College of Technology Coimbatore
Thiagarajar College Madurai
Government College of Engineering Theni
Cochin University
NITIE Mumbai
NIT Puducherry
NIT Warangal

**Companies:**

DRDO Cochin
Banca Sella Chennai
IBM Chennai
Goldman Sachs Bangalore
Blackboard Information technology India Pvt Ltd Chennai

**Comment by bravegnu** [comment]
And this too https://pehia.org/

**Comment by smiraldr** [comment]
I am a student of SRM Institute of Science and Technology and i have reached out to some of the student community too for PyCon and i am giving them constant updates on PyCon. Many are interested and will buy tickets for the same.

**Comment by bravegnu** [comment]
Thanks @smiraldr!

**Comment by ganeshkumartk** [comment]
Hey Guys, I can promote PyCon for IIIT Kancheepuram. Will reach out to student communities for same 👍

**Comment by bravegnu** [comment]
Thanks @CoDeRgAnEsh !
