### ISSUE TITLE
Twitter Description Update

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#45]
Twitter description should contain the event date and venue.

**Comment by gnurenga** [comment]
@bravegnu  Twitter is updated

**Comment by bravegnu** [comment]
Can we try this?

``````
PyCon India 2019 is happening in Chennai | Oct 12-13: Conference | Oct 14: Workshops | Oct 14, 15: Devsprints
``````

**Comment by bravegnu** [comment]
Or better yet:

``````
Oct 12-13: Conference | Oct 14: Workshops | Oct 14-15: Devsprints
``````

Change the Twitter user location to Chennai India. This is based on https://twitter.com/PyColorado

**Comment by gnurenga** [comment]
Twitter is updated like below

> Oct 12-13: 🎙️Conference | Oct 14: 👩‍🏫👨‍🏫Workshops | Oct 14-15: 👟Devsprints

**Comment by bravegnu** [comment]
Drop "PyCon India 2019 will be held in Chennai. " Change the location in Twitter instead.

**Comment by gnurenga** [comment]
@bravegnu done

**Comment by bravegnu** [comment]
Also "#PyConIndia" can be dropped?

**Comment by gnurenga** [comment]
"#PyConIndia" is dropped

**Comment by gnurenga** [comment]
Done
