### ISSUE TITLE
LinkedIn group description update

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#47]
The PyCon India LinkedIn group description https://www.linkedin.com/groups/3203762/ needs to be updated, with the 2019 conference details.

**Comment by gnurenga** [comment]
## Previous description 
`Discussions about organizing Pycon India, talk proposals, registrations, sponsors and other details. Join in if you are a delegate attending Pycon India 2018, a current or prospective sponsor, organizer or volunteer or a Python enthusiast willing to join our discussions and contribute his/her voice to the event!`

## Request for New Description
Discussions about organizing PyCon India, talk proposals, registrations, sponsors and other details. Join in if you are a delegate attending PyCon India 2019, a current or prospective sponsor, organizer or volunteer or a Python enthusiast willing to join our discussions and contribute his/her voice to the event!

PyCon India 2019, is happening on Oct 12-15, at Chennai. More details at https://in.pycon.org/2019/

**Comment by bravegnu** [comment]
@gnurenga Edited the message. Changed Pycon to PyCon. And added date and venue.

**Comment by gnurenga** [comment]
Sent mail to Anand

**Comment by gnurenga** [comment]
LinkedIn PyCon India user group info is updated. Closing this issue.
