### ISSUE TITLE
Create Event in Facebook

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#48]
A new event needs to be created for PyCon India 2019 in Facebook: https://www.facebook.com/pg/PyConIndia/events/?ref=page_internal

**Comment by gnurenga** [comment]
Facebook event is created https://www.facebook.com/events/168952034057586/

**Comment by bravegnu** [comment]
Can we create 3 separate events: Conference, Workshop and Devsprints. The current event can be converted for the conference alone. And 2 separate events can be created for the Workshop and Devsprints. This will make the dates and the venues more clearer.

**Comment by gnurenga** [comment]
@bravegnu  updated the facebook with three events.
1. https://www.facebook.com/events/168952034057586/
2. https://www.facebook.com/events/884786628519593/
3. https://www.facebook.com/events/422743604954265/

**Comment by gnurenga** [comment]
Done and closing the issue
