### ISSUE TITLE
Require a graphic designer for Social media post

### ISSUE THREAD

**Issue by Thedijje** [pythonindia/inpycon2019-tasks#5]
Hi Everyone and @babuenir

We need a graphic designer for working with social media team to make updates, posts for promotion. We are planning for Facebook/Twitter and Linkedin promotion so their specs should be used.

Please revert/comment on issues if you can make it and be part of Pycon India 2019.

**Comment by abhishekmishragithub** [comment]
@Thedijje i know graphic designer who can design posters and banners. Please let me know on same.

**Comment by Thedijje** [comment]
Hi @abhishekmishragithub 
That would really be great, please mention them here or pm me on Telegram, I am having the same username there. I'll try to connect him with others in the team as well.

**Comment by bravegnu** [comment]
> @Thedijje i know graphic designer who can design posters and banners. Please let me know on same.

@astronomersiva has posted a form on the PyCon India mailing list. You can ask them to sign up there?

**Comment by Thedijje** [comment]
thank you @astronomersiva 
I got connected and shared form for the same. Will guide him through work as soon as he signs up.

**Comment by abhishekmishragithub** [comment]
@Thedijje I have shared you on twitter, couldn't find you in Telegram

**Comment by iamaravindsekar** [comment]
Hi @Thedijje this is Aravind, Abhishek's friend... The graphic designer he was telling you about, I would like to work on the social media promotion campaign

**Comment by Thedijje** [comment]
Hi @noblebatman 
Thanks for your initiative, please check our current requirement at https://github.com/pythonindia/inpycon2019-tasks/projects/1 and please connect me in telegram with same username @thedijje .
Looking forward.

**Comment by bravegnu** [comment]
Given that we have a team in place now, this issue can be considered resolved.
