### ISSUE TITLE
Identify Sound and light vendors

### ISSUE THREAD

**Issue by arunedwin-imaginea** [pythonindia/inpycon2019-tasks#50]
cat: venue-logistics

**Comment by arunedwin-imaginea** [comment]
Have identified someone who could help with sound, light, and acoustics in hall partition. 
Name: Akash
Mobile no : 9003150034

**Comment by bravegnu** [comment]
The AV needs to cater to the following:

  * Stage setup and backdrop for the 3 talk tracks
  * Projectors / LED walls for the 3 talk tracks
  * Microphone and speakers for the 3 talk tracks
  * Recording for the 3 talk tracks

**Comment by bravegnu** [comment]
Thanks @arunedwin-imaginea for the suggestion!

**Comment by gnurenga** [comment]
At PyCon US two important Keynote recorded video was missed, Below is the twitter thread discuss about that issue, We also need to be careful with backups.
https://twitter.com/pycon/status/1128031227569745920
