### ISSUE TITLE
Improve the CoC

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#54]
The Code of Coduct needs a little bit cleanup:

  * The long version and short version look very similar. The short version should be really short, and provide the gist. And the long version should have all the details.

  * The procedure to handle CoC violations, and the escalation procedure, should be clearly documented.

**Comment by sharmi** [comment]
Have taken the main points from our code of conduct to be highlighted on the registration page. 

I agree to the <a href="https://in.pycon.org/2019/code-of-conduct.html">Code of Conduct.</a>

* Be kind and sensitive to the people around me and avoid any kind of offensive behavior. Sexist, racist or any other form of exclusionary or offensive jokes/content/clothing or excessive public swearing are not appropriate at any venue of PyCon India.

* PyCon India is dedicated to providing a harassment-free conference experience for everyone, regardless of age, gender, sexual orientation, physical appearance, disability, race, religion or employment. We don’t tolerate harassment of attendees in any form.

* Attendees violating these rules may be asked to leave the conference without a refund at the sole discretion of the conference organizers.

**Comment by sharmi** [comment]
Report and Resolution Guide : Django - https://www.djangoproject.com/conduct/reporting/

**Comment by sharmi** [comment]
The shorter code of Conduct will be placed on the ticket registration page just before they pay.

The aim of the short code of conduct

* Emphasize that we take any violation our CoC seriously
* Be easy to read, so people's eyes don't glaze over.
* Highlight the most important points of our CoC

This one is derived from TED's code of conduct
https://www.ted.com/attend/conferences/registration-policies/code-of-conduct

**Comment by sharmi** [comment]
We invite you to come to PyCon India 2019 in a spirit of curiosity, friendliness, open-mindedness, and respect. We will not tolerate harassment in any form.

At the PyCon India venue and related online forums, you agree to:

- Be kind and sensitive to the people around you and respect the boundaries of other attendees.
- Attempt to resolve difference of opinions peacefully
- Avoid harassment, exclusionary or offensive behaviour of any kind. This includes but is not limited to offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention. 

More information on <a href="https://in.pycon.org/2019/code-of-conduct.html"> Code of Conduct </a> and <a href="https://in.pycon.org/2019/reporting-guide.html"> Reporting Guide and Steps for Resolution</a>.
