### ISSUE TITLE
Add the conference to Python Events Calendar

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#55]
We need to get our event added over here: https://wiki.python.org/moin/PythonEventsCalendar

**Comment by abhishekmishragithub** [comment]
@bravegnu please assign this to me. I have already sent mail to events team. I do not have privilege for self assigning the issue.

**Comment by bravegnu** [comment]
@abhishekmishragithub Any update on this?

**Comment by abhishekmishragithub** [comment]
> @abhishekmishragithub Any update on this?

@bravegnu I've been following with event team. I had already send mail to them (events@python.org) for same. Still i did not get any response from them.

I followed the process mentioned below:
https://wiki.python.org/moin/PythonEventsCalendar

**Comment by bravegnu** [comment]
OK, let's wait for their response.

**Comment by abhishekmishragithub** [comment]
Added the conference to Python Events Calendar.
Links : 
https://www.python.org/events/python-events/?page=4
https://www.python.org/events/python-events/845/
