### ISSUE TITLE
Create blog post on how to make the most out of conference

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019-tasks#58]
Hopefully sharing it out with minority groups will motivate them to join. The aims of the post are

* Showcase different possibilities available in a conference.
* minimum criteria for attending a conference ( === null) or who is it for( == everybody )
* a brief mention of facilities available
* Links to journals about previous conferences

**Comment by abhishekmishragithub** [comment]
are we looking for any blogger for this ?
anyone working on this ?

**Comment by sharmi** [comment]
No one is on this task right now,Abhishek

**Comment by amrrs** [comment]
Hey @sharmi , Do you have any such sample work from any other Pycon, With some sample, I can probably pick it up to make a draft!

**Comment by bravegnu** [comment]
@amrrs How about this https://realpython.com/pycon-guide/ ? It needs to be customized to PyCon India.
