### ISSUE TITLE
Adding meetup event on conference in meetup groups in India

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#59]
Approach event organizers to create an event for PyCon India 2019 Conference
- [x] Chennaipy
- [x] PyLadies Chennai
- [x] Bangpypers
- [ ] HydPy
- [x] DelhiPy
- [x] KovaiPy

## To Do 
* Reach out to possible meetup groups

**Comment by bravegnu** [comment]
Please check https://www.meetup.com/Chennaipy/events/261292751/

**Comment by bravegnu** [comment]
We can also add Kovaipy and may be Pyladies meetup groups as well.

**Comment by niharikakrishnan** [comment]
PyCon India 2019 event has been added to PyLadies Chennai Meetup Group.
[https://www.meetup.com/pyladieschennai/events/261445255/](https://www.meetup.com/pyladieschennai/events/261445255/)

**Comment by bravegnu** [comment]
Thanks @niharikakrishnan

**Comment by bravegnu** [comment]
Sent requests to Kovaipy, HydPy, PyLadies Delhi, Mumbai Python User Group, Pune Python User Group, Kochi Python User Group and Bengaluru PyLadies.
