### ISSUE TITLE
Add PyCon India 2019 conference as up coming events in Chennaipy Website Dashboard

### ISSUE THREAD

**Issue by gnurenga** [pythonindia/inpycon2019-tasks#60]

**Comment by gnurenga** [comment]
A pull request is created for this issue https://github.com/Chennaipy/website/pull/141

**Comment by gnurenga** [comment]
Landing page look like below
![landing-page](https://user-images.githubusercontent.com/3196294/57135236-4def6e80-6dc6-11e9-88d4-e780ad1cbd41.png)

**Comment by bravegnu** [comment]
I have added a comment @gnurenga Can you please fix it?

**Comment by gnurenga** [comment]
Done @bravegnu

**Comment by gnurenga** [comment]
Since the dashboard change is merged I am closing this issue.
