### ISSUE TITLE
Post for Workshop CFP announcement

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#61]
![workshop-cfp](https://user-images.githubusercontent.com/1171852/57174610-184a9400-6e5f-11e9-8245-cf2f81e52205.png)

``````
Workshop CFP is now open! Please visit https://in.pycon.org/cfp/workshops-2019/proposals/ to submit your proposal.

#Python #PyConIndia2019
``````

**Comment by bravegnu** [comment]
@zerothabhishek @astronomersiva @dudewhocode Please +1.

**Comment by bravegnu** [comment]
Email template for Python meetup groups.

Subject: PyCon India 2019: Call for Workshop Proposals
Body:

Hi Everyone,
CFP for workshops is now open! Workshops happen on Oct 14th (3rd
day of PyCon India 2019). Please visit
https://in.pycon.org/cfp/workshops-2019/proposals/ to submit your
workshop proposal.

For the uninitiated, PyCon India 2019 is happening in Chennai, between
Oct 12 and Oct 15. For more details, about the event, please visit
http://in.pycon.org/

Don't want to miss an update from us? Subscribe for announcements
at http://in.pycon.org/

Regards,
{{ your-name }}
PyCon India 2019, Organizing Team

**Comment by bravegnu** [comment]
Email template for inpycon-announce.

Subject: PyCon India 2019: Call for Workshop Proposals
Body:

Hi Everyone,
CFP for workshops is now open! Workshops happen on Oct 14th (3rd
day of PyCon India 2019). Please visit
https://in.pycon.org/cfp/workshops-2019/proposals/ to submit your
workshop proposal.

For the uninitiated, PyCon India 2019 is happening in Chennai, between
Oct 12 and Oct 15. For more details, about the event, please visit
http://in.pycon.org/

Regards,
{{ your-name }}
PyCon India 2019, Organizing Team

**Comment by bravegnu** [comment]
@gnurenga Updated people who have registered for subscriptions to inpycon-announce.

**Comment by bravegnu** [comment]
Email template for other meetup groups.

Subject: PyCon India 2019: Call for Workshop Proposals
Body:

Hi Everyone,
CFP for workshops is now open! Workshops happen on Oct 14th (3rd
day of PyCon India 2019). Please visit
https://in.pycon.org/cfp/workshops-2019/proposals/ to submit your
workshop proposal.

PyCon India is India's annual conference for the Python programming
language. The event is happening in Chennai this year, on Oct 12 -
15. About 1200 people, from across India, are expected to participate
in this event. Here are some quick links:

  * For more details, about the event, visit https://in.pycon.org/
  * Submit your workshop proposal at
    https://in.pycon.org/cfp/2019/proposals/
  * Submit your talk proposal at
    https://in.pycon.org/cfp/2019/proposals/
  * Tickets will open on 1st June. Stay tuned for updates by
    subscribing to our announcements at https://in.pycon.org/

Regards,
{{ your-name }}
PyCon India 2019, Organizing Team

**Comment by bravegnu** [comment]
Sent mails to InPyCon, Chennaipy, HydPy, Python Pune and PyDelhi, so far.

**Comment by rajkumartreads** [comment]
Reached KovaiPy.

**Comment by gnurenga** [comment]
## Mailed to below groups
- [x] Chennai Geek Night 
- [x] IOT geeks
