### ISSUE TITLE
Pro Tip for introverts at a conference

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#62]
We need to RT this with a message suitable for PyCon India https://twitter.com/valeriecodes/status/1124760525441839105

**Comment by bravegnu** [comment]
Tweet:

If you are introverted, you can make best use of PyCon India, by becoming a speaker. Visit https://in.pycon.org/ to submit your talk / workshop proposal.

#Python #PyConIndia2019

**Comment by gnurenga** [comment]
Done. https://twitter.com/pyconindia/status/1125702846492565504
