### ISSUE TITLE
Create speaker recommendation form

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019-tasks#64]
Create a form that we can circulate among meetup groups to recommend speakers.

The goal is to get speakers from diverse backgrounds and on diverse topics.

Ideally we should be able to get the speaker's name, meetup group name, topic that they had spoken on, areas of expertise, phone and/or email id, the recommender's name.

The most important fields would be speaker's name and contact info.

**Comment by ParitoshikPaul** [comment]
@sharmi: Can we use google forms, if yes what account needs to be linked to get the responses ?

**Comment by laxmena** [comment]
It is possible to transfer the ownership of Google Forms i guess.

**Comment by laxmena** [comment]
Also consider typeform and surveymonkey. Need to evaluate if free tier is sufficient for our needs.

**Comment by bravegnu** [comment]
We have already created this form: https://forms.gle/zCuNk3pAHXPjrURq9

We now have to reach out to organizers for various meetup groups, to recommend speakers who have done talks at their meetups.

**Comment by bravegnu** [comment]
> We now have to reach out to organizers for various meetup groups, to recommend speakers who have done talks at their meetups.

Especially people from diverse backgrounds.
