### ISSUE TITLE
Tweet: Invite women speakers to submit proposals

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#65]
![women-speakers](https://user-images.githubusercontent.com/1171852/57341542-770e5700-7158-11e9-9b99-eb15f6cc186b.png)

Have a favourite women speaker / blogger / coder, who you think should take the stage at #PyConIndia2019?

Give them a gentle nudge, by tagging them. RT to reach more #WomenInTech #PyLadies #WomenWhoCode #WWCode #DjangoGirls #WIDS

Submit proposals at https://in.pycon.org/

**Comment by aditiprakash** [comment]
Other suggested hashtags-

#girlswhocode #stem #womanprogrammers #techladies #WomeninSTEM

**Comment by bravegnu** [comment]
@aditiprakash Can you let me know which are the top 10 hash tags (sorted), because we have already hit the 280 character limit.

**Comment by sharmi** [comment]
#womentechmakers

**Comment by bravegnu** [comment]
Based on @sharmi suggestions, I think we can tag top women-in-tech groups, who are more likely to retweet us, and get us better visibility.

**Comment by bravegnu** [comment]
![women-speakers](https://user-images.githubusercontent.com/1171852/57341542-770e5700-7158-11e9-9b99-eb15f6cc186b.png)
``````
Have a favorite women speaker / blogger / coder who you think should take the stage at #PyConIndia2019?

Give them a gentle nudge, by tagging them.

Please RT #Python @WomenInTech @PyLadies @WomenWhoCode @DjangoGirls @WomenTechmakers

Submit proposals at https://in.pycon.org/ 
``````

**Comment by sharmi** [comment]
Sounds great Vijay, The groups you have tagged are international ones. Here are the handles of local chapters that have been active within last year. I am hope if we tweet to the parent groups, the local chapters will pick them up. If not, we can tweet to them again.

@AnitaBorg_India @WWCodePune @WTMSriLanka @WooTechology 	@Wwcodesingapore 	
 @DjangoGirlsBLR @GirlsGurgaon	@djangogirlspune	@djangongp @WWCode_Delhi @WWCodeChennai @WWCodeBangalore @WTMAhmedabad @GDGAhmedabad @pehiaorg

**Comment by bravegnu** [comment]
Tweeted https://twitter.com/pyconindia/status/1126404549093150722

**Comment by bravegnu** [comment]
> Sounds great Vijay, The groups you have tagged are international ones. Here are the handles of local chapters that have been active within last year. I am hope if we tweet to the parent groups, the local chapters will pick them up. If not, we can tweet to them again.
> 
> @AnitaBorg_India @WWCodePune @WTMSriLanka @WooTechology @Wwcodesingapore
> @DjangoGirlsBLR @GirlsGurgaon @djangogirlspune @djangongp @WWCode_Delhi @WWCodeChennai @WWCodeBangalore @WTMAhmedabad @GDGAhmedabad @pehiaorg

OK
