### ISSUE TITLE
Keynote Speaker Announcement

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#70]
![keynote-speaker](https://user-images.githubusercontent.com/1171852/57641440-a39bf600-75d2-11e9-9e74-acde3a78022c.png)

``````
We are happy to announce that Ines Montani @_inesmontani is a keynote speaker for PyCon India 2019! https://in.pycon.org/blog/2019/announcing-keynote-speaker-for-pycon-india-2019-ines-montani.html

#PyConIndia2019 #Python
``````

**Comment by bravegnu** [comment]
We might want to add a blog link, once Siva gets the article on the blog.

**Comment by gnurenga** [comment]
I remove this handle @_inesmontani so that i can post in Facebook. @bravegnu  Is that ok ?

**Comment by bravegnu** [comment]
OK @gnurenga
