### ISSUE TITLE
Fixup dates on Facebook page

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#78]
The date on the Facebook page https://www.facebook.com/pg/PyConIndia/about/?ref=page_internal needs to be updated.

**Comment by gnurenga** [comment]
Fixed @bravegnu Could you please check it ?

**Comment by bravegnu** [comment]
Can we just make it "Oct 12 - 15"?

**Comment by gnurenga** [comment]
Done
