### ISSUE TITLE
Post for CFP announcement.

### ISSUE THREAD

**Issue by Thedijje** [pythonindia/inpycon2019-tasks#8]
### Post for CFP announcement.
Without image or text which to be supplied with the image.
CFP opens at :
Last date for CFP :

**Comment by bravegnu** [comment]
![cfp](https://user-images.githubusercontent.com/1171852/55592871-7c424580-5757-11e9-87a1-0203e179dda9.png)
``````
Vanakkam!

Our Call For Proposals is now open 🥁 Get those filter coffees ☕️ brewing  and power up your brains. 

We would like to encourage content from diverse walks of life and increase the participation of under-represented groups. You can help us by encouraging your friends, family and colleagues to submit talks

Read more about the CFP process and submit talks at https://in.pycon.org/2019/cfp.html.

#Python #PyConIndia2019
``````

**Comment by bravegnu** [comment]
Mail template for Python User Groups, who already know about PyCon
India.

``````
Subject: CFP is Open for PyCon India 2019!
``````

Hi Everyone,
Our Call For Proposals is now open! You can submit your talk at https://in.pycon.org/2019/cfp.html

We would like to encourage content from diverse walks of life and increase the participation of under-represented groups. You can help us by encouraging your friends, family and colleagues to submit talks. Read more about the CFP process and submit talks at https://in.pycon.org/2019/cfp.html

Please be noted that call for workshops and posters will be opened shortly. Stay tuned for updates! If you have not done so, make sure you subscribe to our updates at http://in.pycon.org/

Regards,
{{ your-name }}
On behalf of PyCon India 2019, Organizing Team

**Comment by bravegnu** [comment]
For non-Python user groups, a small introduction about PyCon India would be helpful.

**Comment by bravegnu** [comment]
Template for non-Python user groups.

``````
Subject: CFP is Open for PyCon India 2019!
``````

Hi Everyone,
Our Call For Proposals is now open! You can submit your talk at https://in.pycon.org/2019/cfp.html

For the uninitiated, PyCon India is India's premier conference on using and developing the Python programming language.  This year the conference is happening in the Chennai Trade Centre, on October 12 and 13, 2019. About 1200 Pythonistas from all over India are expected to participate in the event.  For more details about the event please visit https://in.pycon.org/

We would like to encourage content from diverse walks of life and increase the participation of under-represented groups.  Read more about the CFP process and submit talks at https://in.pycon.org/2019/cfp.html

Please be noted that call for workshops and posters will be opened shortly. Stay tuned for updates! If you have not done so, make sure you subscribe to our updates at http://in.pycon.org/

Regards,
{{ your-name }}
On behalf of PyCon India 2019, Organizing Team

**Comment by bravegnu** [comment]
Template for Individuals

``````
Subject: Talk Proposal for PyCon India 2019!
``````

Hi {{ name }},
Hope you are doing fine! Just wanted to let you know that call for proposals for PyCon India 2019 has opened!

PyCon India is the annual gathering of Pythonistas from across India. This year the conference is happening in Chennai, on Oct 12 and 13. It will be great if you can submit a talk proposal, and share your ideas / present your work at the conference.

Do consider submitting a talk proposal at https://in.pycon.org/2019/cfp.html

Please be noted that call for workshops and posters will be opened shortly. You can subscribe to our updates at http://in.pycon.org/

Regards,
{{ your-name }}
On behalf of PyCon India 2019, Organizing Team

**Comment by bravegnu** [comment]
Template for Colleges / Institutions / Organizations

``````
Subject: Talk Proposals for PyCon India 2019!
``````

Hi {{ name }},
Hope you are doing fine! Call for proposals for PyCon India 2019 has opened!

PyCon India is the annual gathering of Pythonistas from across India. This year the conference is happening in Chennai, on Oct 12 and 13. It will be great to see developers from {{ org-name }} share their ideas / present their work at the conference.


Please forward this information to groups within {{ org-name }}. People can submit proposals at https://in.pycon.org/2019/cfp.html

Please be noted that call for workshops and posters will be opened shortly. You can subscribe to our updates at http://in.pycon.org/

Regards,
{{ your-name }}
On behalf of PyCon India 2019, Organizing Team

**Comment by gnurenga** [comment]
Team kindly  tick check box once you done with the post

- [x]  @gnurenga
- [x]  @abhishekmishragithub
- [x]  @aaronstone007
- [ ]  @shivank98
- [x]  @TanviKumar
- [x]  @Dhanya-Abhirami
- [ ] @niharikakrishnan
- [ ]  @py-ranoid

**Comment by aaronstone007** [comment]
> Team kindly tick check box once you done with the post
> 
> * [ ]   @gnurenga
> * [ ]   @abhishekmishragithub
> * [ ]   @aaronstone007
> * [ ]   @Shivank98
> * [ ]   @TanviKumar
> * [ ]   @Dhanya-Abhirami
> * [ ]  @niharikakrishnan
> * [ ]   @py-ranoid

**Comment by bravegnu** [comment]
Folks, these are just templates. Please feel to tweak them to suite the community you are posting to.

**Comment by TanviKumar** [comment]
> > Team kindly tick check box once you done with the post
> > 
> > * [ ]    @gnurenga
> > * [ ]    @abhishekmishragithub
> > * [ ]    @aaronstone007
> > * [ ]    @Shivank98
> > * [ ]    @TanviKumar
> > * [ ]    @Dhanya-Abhirami
> > * [ ]   @niharikakrishnan
> > * [ ]    @py-ranoid

**Comment by bravegnu** [comment]
Please note that, we have already posted to Chennaipy, Bangpypers, Python Pune and Hyderabad Python mailing lists.

**Comment by Dhanya-Abhirami** [comment]
> Team kindly tick check box once you done with the post
> 
> * [ ]   @gnurenga
> * [ ]   @abhishekmishragithub
> * [ ]   @aaronstone007
> * [ ]   @Shivank98
> * [ ]   @TanviKumar
> * [ ]   @Dhanya-Abhirami
> * [ ]  @niharikakrishnan
> * [ ]   @py-ranoid

**Comment by abhishekmishragithub** [comment]
> Team kindly tick check box once you done with the post
> 
> * [ ]   @gnurenga
> * [ ]   @abhishekmishragithub
> * [ ]   @aaronstone007
> * [ ]   @Shivank98
> * [ ]   @TanviKumar
> * [ ]   @Dhanya-Abhirami
> * [ ]  @niharikakrishnan
> * [ ]   @py-ranoid

**Comment by bravegnu** [comment]
Folks please do not copy the checklist, update the original check list, if you have posted.
