### ISSUE TITLE
Flyers for offline promotion

### ISSUE THREAD

**Issue by abhishekmishragithub** [pythonindia/inpycon2019-tasks#80]
Paper Pamphlet design for promotion work

**Comment by agnes-joseph** [comment]
@abhishekmishragithub Can I get further details on this?

**Comment by abhishekmishragithub** [comment]
@agnes-joseph it could be something like this, where in one flyer we can all PyCon Detail.


![poster_whatsapp](https://user-images.githubusercontent.com/38150419/59008829-1bafb180-8849-11e9-95e8-669ec7dbae3d.jpg)

**Comment by bravegnu** [comment]
More examples:

<img src="https://p-u.popcdn.net/attachments/images/000/009/927/large/new_poster_pycon_thailand1111.png?1528283671"/>

<img src="https://lh5.googleusercontent.com/vyjJAil3hoGxsqPc7BE5sWQGf1enSZ_xRjKfRzoiGVu4UzxtAXITVarN-kMotsxkFB68DGdB5jdrh1ffwOM-SAQyFEEfqzhEucPnhCYp788vwpjEL1C8jlVpaE3v7nz6JABRvogz"/>

**Comment by abhishekmishragithub** [comment]
@bravegnu you got it better 👍

**Comment by agnes-joseph** [comment]
Thanks for the example @abhishekmishragithub and @bravegnu . By when would you need this? Also, can I get the required dimensions?

**Comment by bravegnu** [comment]
@agnes-joseph A4 should work.

**Comment by bravegnu** [comment]
@agnes-joseph @astronomersiva Just wanted to check on this.

**Comment by agnes-joseph** [comment]
Will try to work on this in the weekend, by when do you need it? @bravegnu

**Comment by bravegnu** [comment]
Monday should work. Next time around *you* can let us know when it can be done. We can work it from there.

**Comment by agnes-joseph** [comment]
Sure @bravegnu Will keep that in mind :)

**Comment by agnes-joseph** [comment]
![PyCon Poster](https://user-images.githubusercontent.com/10452872/59555463-39f77900-8fd0-11e9-9b7b-34d917acd86e.jpg)


Came up with this as a rough draft, should anything else be added? Also, which file format should I send it as?

**Comment by bravegnu** [comment]
The file format: PDF and PNG

The content looks sufficient. Here are few changes that needs to be made, in terms of the design.

  1. For the top background, we can drop the outline from the logo and use a different shape. The idea is to avoid playing around with the logo too much.

  2. The bottom background outline can be retained as such, but please use the outline from the latest version of the logo. You can get the latest SVGs from https://github.com/pythonindia/inpycon2019-tasks/tree/master/art

  3. I have marked a few places in the image below, that does not have sufficient contrast.

![poster](https://user-images.githubusercontent.com/1171852/59558294-895b9a80-900c-11e9-97dd-0acbff5e3c65.jpg)

**Comment by bravegnu** [comment]
>     1. For the top background, we can drop the outline from the logo and use a different shape. The idea is to avoid playing around with the logo too much.

Or if we would like to keep the symmetry between the top and bottom outline, the elements within the top outline can be dropped.

But the outlines are themselves actually a good idea, because if the poster is affixed on a noticeboard it will attract attention.

**Comment by agnes-joseph** [comment]
@bravegnu Thanks for the feedback. Will make the suggested changes and upload.
Completely forgot about the logo! I'll replace it

**Comment by agnes-joseph** [comment]
![PyCon Poster 2](https://user-images.githubusercontent.com/10452872/59574670-ccce0b80-90d5-11e9-953d-cac9c2dc7e7a.jpg)
Made the suggested changes and cleaned up the layout. Again, this is a rough draft, do let me know if it's fine. I'll make some small changes and push the PDF version

**Comment by bravegnu** [comment]
Looks good @agnes-joseph Can we also have Grayscale variant (preferrably with a white background, instead of the shaded background), suitable for printing on standard laser printer.

**Comment by agnes-joseph** [comment]
[Pycon 2019.zip](https://github.com/pythonindia/inpycon2019-tasks/files/3316881/Pycon.2019.zip)
Included RGB CYMK and Greyscale variant

**Comment by bravegnu** [comment]
Thanks @agnes-joseph One final change request, can we move the background icons to the left hand side? Atleast in the grayscale version it makes some of the text hard to read.

**Comment by agnes-joseph** [comment]
[PyCon Poster 2.zip](https://github.com/pythonindia/inpycon2019-tasks/files/3327850/PyCon.Poster.2.zip)
Here you go!

**Comment by bravegnu** [comment]
A few more fixes before we can finalize:
  * Speakers -> "Keynote Speakers" or just "Keynote"
  * David Beazley's description has been truncated half-way through.

**Comment by agnes-joseph** [comment]
Sure. Will make the changes by tonight

**Comment by agnes-joseph** [comment]
[Python Poster.zip](https://github.com/pythonindia/inpycon2019-tasks/files/3331081/Python.Poster.zip)

**Comment by agnes-joseph** [comment]
[Poster for Pycon.zip](https://github.com/pythonindia/inpycon2019-tasks/files/3331246/Poster.for.Pycon.zip)
