### ISSUE TITLE
Poster for Ticket Announcement

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#81]
We will be making an announcement for tickets shortly. We will need a social media poster for announcing the tickets.

**Comment by bravegnu** [comment]
@astronomersiva Can you get somebody to work on this?

**Comment by astronomersiva** [comment]
Yup

**Comment by astronomersiva** [comment]
Courtesy @agnes-joseph 

![Ticket Announcement](https://user-images.githubusercontent.com/7725225/58743536-f853c380-8450-11e9-97f4-4ce6ddd29f04.png)

I'll upload the PSD in a while.

**Comment by bravegnu** [comment]
@astronomersiva This sure is amazing work. One nit-pick: Can we change the Python heads to the PSF version?

**Comment by astronomersiva** [comment]
![My Post](https://user-images.githubusercontent.com/7725225/58748166-1beb2e00-8492-11e9-9969-bb9ce50a44af.png)

Took a shot at editing this since Agnes isn't available now. I have created a PR with the PSD file as well.

**Comment by bravegnu** [comment]
Thanks @astronomersiva!

**Comment by bravegnu** [comment]
![post](https://user-images.githubusercontent.com/1171852/58795563-9fcf2280-8618-11e9-880e-bd45701f57f4.png)

Tickets are live at https://in.pycon.org/

#Python #PyConIndia2019

**Comment by abhishekmishragithub** [comment]
> ![My Post](https://user-images.githubusercontent.com/7725225/58748166-1beb2e00-8492-11e9-9969-bb9ce50a44af.png)
> 
> Took a shot at editing this since Agnes isn't available now. I have created a PR with the PSD file as well.

+1

**Comment by abhishekmishragithub** [comment]
> ![post](https://user-images.githubusercontent.com/1171852/58795563-9fcf2280-8618-11e9-880e-bd45701f57f4.png)
> 
> Tickets are live at https://in.pycon.org/
> 
> #Python #PyConIndia2019

+1
