### ISSUE TITLE
Tweet for invitation to use childcare

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019-tasks#86]
If there is enough demand, PyCon India wants to provide Child Care facility. Are you a parent of young kids? Do you need Child Care in PyCon India 2019? If yes, please tag yourself.

**Comment by bravegnu** [comment]
This is like addressing people who are attending PyCon India 2019, and asking them do they want child care. A better way to phrase it would be:

Are you a parent of young kids? Do you think that a child care option at PyCon India 2019, would increase 'your' chances of participating in the conference? If yes, please hit like.

**Comment by bravegnu** [comment]
Tweet with Poll:

Are you a parent of young kids? Do you think that a child care option at PyCon India 2019, would increase 'your' chances of participating in the conference?

* Yes
* No

**Comment by sharmi** [comment]
Are you a parent of young kids? 

Do you think that a child care option at PyCon India 2019, will increase 'your' chances of participating in the conference?
Vote yes.

**Comment by sharmi** [comment]
Tweet with Poll:

Are you a parent of young kids? Do you think that a child care option at PyCon India 2019, would increase 'your' chances of participating in the conference?

-  Yes
-  No

#pyladies #womenwhocode #WomenTechMakers

**Comment by bravegnu** [comment]
Poll results are here: https://twitter.com/pyconindia/status/1133246897890648064
