### ISSUE TITLE
Tweet for interest to kids workshop

### ISSUE THREAD

**Issue by sharmi** [pythonindia/inpycon2019-tasks#89]
Tweet with Poll:

Do you have kids older than 7? Would having a two day kids science/programming workshop increase 'your' chances of participating in the conference?

    Yes, having a Kids Science/Programming Workshop will be helpful
    No

#pyladies #womenwhocode #WomenTechMakers

**Comment by bravegnu** [comment]
@sharmi I guess we can sense the community, from the previous tweet. People are interested if we inform them early on. So I guess we can start looking for partners, come up with an engagement plan and it include as part of the ticketing process.
