### ISSUE TITLE
Social Media Attendee Badge

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#92]
Create a badge for use on social media, so that people can show off their participation to other users. We will similarly need a speaker badge, as well.

**Comment by hellozee** [comment]
I would love to give it a shot but do you have any sample which can help me? :)

**Comment by bravegnu** [comment]
@astronomersiva Is also working on this.

@hellozee You can try searching for images with keywords "I am attending badge"

**Comment by hellozee** [comment]
![pycon badge](https://user-images.githubusercontent.com/12135951/58873877-f0ac4d00-86e4-11e9-9742-c828fa065951.png)

**Comment by astronomersiva** [comment]
@hellozee, thanks for this. 

Facebook has a [badge creator](https://developers.facebook.com/products/frame-studio/). We need to ensure that the badge suits both square and round pictures.

**Comment by bravegnu** [comment]
@astronomersiva I am looking for something along the lines of http://2016.placonference.org/web-badges/

**Comment by astronomersiva** [comment]
@bravegnu, to be frank, I don't think many people will have this as their entire profile picture/cover picture. 

Facebook's style is simple and easy to spread. We can probably have both but not doing the usual FB badge won't be a good choice.

**Comment by laxmena** [comment]
@bravegnu , The Images in the link, don't they all look similar? Differentiating the tags for attendees, presenters and everyone could be handy. This is my suggestion, what's your take on this?

**Comment by hellozee** [comment]
@bravegnu @astronomersiva we can have both, I guess, but I am not sure about that facebook badge thing, I don't have a facebook account so no idea how that works.

**Comment by abhishekmishragithub** [comment]
https://in.pycon.org/2010/publicity/

Here is what we had for one of the PyCon India.
