### ISSUE TITLE
Vision Statement, Social Media Announcement

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#93]
![vision-statement](https://user-images.githubusercontent.com/1171852/58603037-d3265000-82ac-11e9-85ef-69eed0f7e7ad.png)

Read more about our vision for PyCon India 2019 at https://in.pycon.org/blog/2019/pycon-india-2019-vision.html

#Python #PyConIndia2019

**Comment by bravegnu** [comment]
![vision-statement](https://user-images.githubusercontent.com/1171852/58604734-17b4ea00-82b3-11e9-80f4-7486d893496f.png)

Read more about our vision for PyCon India 2019 at https://in.pycon.org/blog/2019/pycon-india-2019-vision.html

#Python #PyConIndia2019

**Comment by sharmi** [comment]
+1

**Comment by abhishekmishragithub** [comment]
> ![vision-statement](https://user-images.githubusercontent.com/1171852/58604734-17b4ea00-82b3-11e9-80f4-7486d893496f.png)
> 
> Read more about our vision for PyCon India 2019 at https://in.pycon.org/blog/2019/pycon-india-2019-vision.html
> 
> #Python #PyConIndia2019

Is this final ? @bravegnu

**Comment by bravegnu** [comment]
Waiting for +1s.

**Comment by bravegnu** [comment]
@gnurenga Can you please post this?

**Comment by abhishekmishragithub** [comment]
> ![vision-statement](https://user-images.githubusercontent.com/1171852/58604734-17b4ea00-82b3-11e9-80f4-7486d893496f.png)
> 
> Read more about our vision for PyCon India 2019 at https://in.pycon.org/blog/2019/pycon-india-2019-vision.html
> 
> #Python #PyConIndia2019

+1
