### ISSUE TITLE
Poster for 3 Days to Go

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#94]
Poster for 3 Days to Go for Ticket Announcement.

**Comment by astronomersiva** [comment]
![three-days](https://user-images.githubusercontent.com/7725225/58605574-e7227f80-82b5-11e9-9013-ab38b9f187a9.png)

^Suggestions please

**Comment by astronomersiva** [comment]
![three days to go](https://user-images.githubusercontent.com/7725225/58605652-205aef80-82b6-11e9-8353-b27358e27a62.png)

Suggestions please 😄

**Comment by bravegnu** [comment]
The logo at the bottom left can be made a bit larger.

**Comment by astronomersiva** [comment]
![three-days-to-go](https://user-images.githubusercontent.com/7725225/58606674-1d61fe00-82ba-11e9-8e14-13b287db6084.png)

**Comment by abhishekmishragithub** [comment]
Can we use this in other promotional groups ?

**Comment by bravegnu** [comment]
@abhishekmishragithub Once I get a green signal from the tickets team.

**Comment by abhishekmishragithub** [comment]
> @abhishekmishragithub Once I get a green signal from the tickets team.

Ok, Sir :wink:

**Comment by aditiprakash** [comment]
> ![three-days-to-go](https://user-images.githubusercontent.com/7725225/58606674-1d61fe00-82ba-11e9-8e14-13b287db6084.png)

Is this the final poster?

**Comment by bravegnu** [comment]
The poster is final, I will confirm with the other teams, before we post.

**Comment by bravegnu** [comment]
![3days](https://user-images.githubusercontent.com/1171852/58696758-d3f6d900-83b5-11e9-89bc-d274c0e5834f.png)

Early bird tickets open on 3rd June. 3 days to go!

#Python #PyConIndia2019

**Comment by abhishekmishragithub** [comment]
@bravegnu can we post this ?

**Comment by bravegnu** [comment]
Yes @abhishekmishragithub !
