### ISSUE TITLE
FAQ Announcement

### ISSUE THREAD

**Issue by bravegnu** [pythonindia/inpycon2019-tasks#96]
![faq](https://user-images.githubusercontent.com/1171852/58744700-820c8c80-8463-11e9-8511-0e57aa0b7ac3.png)

PyCon India is 3 events rolled into one mega event. Read our FAQ page to know more about purchasing tickets to each of the events. https://in.pycon.org/2019/faq.html

#PyConIndia2019 #Python

**Comment by abhishekmishragithub** [comment]
+1
